/**
 * Script de seed enrichi — Programme "Maître du sommeil" (30 jours)
 * Programme expert avec contenu avancé, TCC-I approfondie et pratiques contemplatives
 * Exécuter avec : npx tsx scripts/seed-maitre-30j.ts
 */
import "../scripts/load-env.js";
import { drizzle } from "drizzle-orm/mysql2";
import { programDays } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

const MAITRE_DAYS = [
  // ─── SEMAINE 1 : DIAGNOSTIC ET FONDATIONS AVANCÉES ────────────────────────
  {
    dayNumber: 1,
    title: "Jour 1 — Diagnostic complet et objectifs",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Bienvenue dans le programme le plus complet pour maîtriser votre sommeil. 30 jours de transformation intensive basée sur les dernières recherches en neurosciences du sommeil et TCC-I. Aujourd'hui : diagnostic approfondi et définition d'objectifs SMART.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Remplissez le questionnaire ISI (Insomnia Severity Index) pour mesurer votre niveau d'insomnie\n2. Tenez un journal de sommeil détaillé : heure de coucher, temps d'endormissement, nombre et durée des réveils, heure de lever, qualité sur 10\n3. Calculez votre efficacité de sommeil baseline : (temps dormi / temps au lit) × 100\n4. Définissez vos objectifs SMART pour les 30 prochains jours\n5. Méditez 20 min avec la méditation voyage nocturne\n6. Pratiquez 5 cycles de respiration 4-7-8",
    sleepTip: "L'ISI (Insomnia Severity Index) est l'outil de référence utilisé par les cliniciens du sommeil. Un score de 0-7 = pas d'insomnie, 8-14 = insomnie légère, 15-21 = modérée, 22-28 = sévère. Mesurer votre score au Jour 1 et au Jour 30 vous donnera une mesure objective de vos progrès.",
    journalPrompt: "Quel est votre score ISI ? Quelle est votre efficacité de sommeil baseline ? Quels sont vos 3 objectifs SMART pour ce programme ? (Exemple : 'Réduire mon temps d'endormissement à moins de 20 min d'ici le Jour 30')",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 2,
    title: "Jour 2 — Chronobiologie et chronotype avancés",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Votre horloge biologique est contrôlée par le noyau suprachiasmatique (NSC) dans l'hypothalamus. Aujourd'hui, nous explorons les mécanismes moléculaires du rythme circadien et optimisons votre exposition lumineuse selon votre chronotype.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Déterminez votre chronotype précis avec le questionnaire MEQ (Morningness-Eveningness Questionnaire)\n2. Calculez votre fenêtre circadienne optimale selon votre chronotype\n3. Exposez-vous à 10 000 lux de lumière pendant 30 min le matin (lampe de luminothérapie ou soleil direct)\n4. Portez des lunettes anti-lumière bleue dès 19h (ou activez Night Shift sur tous vos écrans)\n5. Méditez 20 min avec la relaxation profonde\n6. Pratiquez 10 min de cohérence cardiaque (5 sec inspiration / 5 sec expiration)",
    sleepTip: "Le chronotype est déterminé par les gènes CLOCK, PER et CRY. La luminothérapie matinale (10 000 lux × 30 min) peut avancer votre horloge de 30 à 60 min par semaine. Pour les couche-tard extrêmes, combinez luminothérapie matinale + restriction de lumière le soir + mélatonine 0.5mg à 21h.",
    journalPrompt: "Quel est votre chronotype selon le MEQ ? Votre emploi du temps actuel correspond-il à votre chronotype naturel ? Quelles contraintes sociales vous empêchent de vivre selon votre rythme ? Comment pourriez-vous les réduire ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 3,
    title: "Jour 3 — Restriction du sommeil intensive",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "La restriction du sommeil est la technique la plus efficace de la TCC-I (taux de réussite 80-90%). Aujourd'hui, nous calculons votre fenêtre de sommeil optimale et mettons en place un protocole strict de restriction.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Calculez votre temps de sommeil moyen des 7 derniers jours (ex : 5h30)\n2. Ajoutez 30 minutes → votre fenêtre de sommeil initiale (ex : 6h00)\n3. Choisissez votre heure de lever NON NÉGOCIABLE (même le week-end)\n4. Calculez votre heure de coucher : lever - fenêtre (ex : 7h - 6h = 1h du matin)\n5. Ne vous allongez PAS avant cette heure, même si vous êtes épuisé(e)\n6. Méditez 20 min avec la méditation de la forêt apaisante\n7. Pratiquez 4 cycles de respiration 4-7-8 au moment de vous allonger",
    sleepTip: "La restriction du sommeil crée une pression homéostatique (accumulation d'adénosine) qui améliore la qualité et réduit le temps d'endormissement. Vous serez fatigué(e) les premiers jours — c'est normal et nécessaire. Évitez les siestes. Augmentez votre fenêtre de 15 min par semaine quand votre efficacité dépasse 85%.",
    journalPrompt: "Quelle est votre fenêtre de sommeil initiale ? Quelle est votre heure de coucher et de lever fixées ? Comment vous êtes-vous senti(e) en attendant votre heure de coucher ? Avez-vous eu envie de faire une sieste aujourd'hui ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 4,
    title: "Jour 4 — Contrôle du stimulus et reconditionnement",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Le contrôle du stimulus reconditionne l'association 'lit = sommeil'. C'est la deuxième technique la plus efficace de la TCC-I. Aujourd'hui, nous appliquons les 6 règles du contrôle du stimulus de manière stricte.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "rain",
    eveningRoutine: "1. Règle 1 : Utilisez le lit UNIQUEMENT pour dormir et les relations intimes\n2. Règle 2 : Ne vous allongez que si vous êtes somnolent(e) (yeux lourds, bâillements)\n3. Règle 3 : Si vous êtes éveillé(e) depuis plus de 20 min, levez-vous immédiatement\n4. Règle 4 : Allez dans une autre pièce et faites une activité calme à faible lumière (lecture, tricot)\n5. Règle 5 : Retournez au lit uniquement quand vous ressentez une somnolence réelle\n6. Règle 6 : Répétez autant de fois que nécessaire cette nuit\n7. Méditez 20 min avec la méditation de la pleine lune avant le coucher",
    sleepTip: "Le contrôle du stimulus exploite le conditionnement classique (Pavlov). Après 2 à 4 semaines de pratique stricte, votre cerveau associera automatiquement 'lit = sommeil profond'. Les premières nuits sont difficiles (vous devrez peut-être vous lever 3-4 fois), mais les résultats sont durables.",
    journalPrompt: "Avez-vous respecté les 6 règles du contrôle du stimulus ? Combien de fois avez-vous dû vous lever cette nuit ? Qu'avez-vous fait en dehors du lit ? Comment vous êtes-vous senti(e) en retournant au lit ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 5,
    title: "Jour 5 — Restructuration cognitive approfondie",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Les pensées dysfonctionnelles sur le sommeil entretiennent l'insomnie. Aujourd'hui, nous utilisons la technique des 5 colonnes de Beck pour identifier et restructurer vos croyances irrationnelles sur le sommeil.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Créez un tableau à 5 colonnes : Situation | Pensée automatique | Émotion | Preuve pour/contre | Pensée alternative\n2. Exemple de situation : 'Il est 2h du matin et je suis éveillé(e)'\n3. Pensée automatique : 'Je ne dormirai jamais, ma journée de demain est fichue'\n4. Émotion : Anxiété (8/10)\n5. Preuves contre : 'J'ai déjà passé de bonnes journées après une mauvaise nuit', 'Mon corps s'adapte'\n6. Pensée alternative : 'C'est une nuit difficile, mais je me reposerai quand même. Demain sera ce qu'il sera.'\n7. Méditez 20 min avec la méditation de gratitude\n8. Notez 5 choses pour lesquelles vous êtes reconnaissant(e)",
    sleepTip: "La restructuration cognitive (thérapie cognitive de Beck) réduit l'anxiété nocturne de 60% en 4 semaines. Les pensées catastrophistes ('Si je ne dors pas 8h, je vais tomber malade') activent l'axe hypothalamo-hypophyso-surrénalien (HHS) et libèrent du cortisol, ce qui maintient l'éveil. Questionner ces pensées brise le cycle.",
    journalPrompt: "Remplissez le tableau à 5 colonnes pour votre pensée automatique la plus fréquente la nuit. Comment vous sentez-vous après avoir questionné cette pensée ? Votre niveau d'anxiété a-t-il diminué ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 6,
    title: "Jour 6 — Hygiène du sommeil scientifique",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "L'hygiène du sommeil va bien au-delà des conseils basiques. Aujourd'hui, nous explorons les 15 règles avancées validées par les dernières méta-analyses, et vous créez votre protocole personnalisé.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Température : chambre à 16-19°C, douche chaude 90 min avant le coucher\n2. Lumière : obscurité totale (masque de sommeil), pas de LED, Night Shift activé dès 19h\n3. Bruit : silence ou bruit blanc/rose (ventilateur, humidificateur)\n4. Caféine : aucune après 14h (demi-vie 5-6h)\n5. Alcool : aucun (perturbe le sommeil paradoxal même en petite quantité)\n6. Exercice : au moins 4h avant le coucher (augmente la température corporelle)\n7. Repas : dîner léger 3h avant le coucher, riche en tryptophane\n8. Écrans : aucun 90 min avant le coucher (pas juste 30 min)\n9. Méditez 20 min avec la méditation voyage nocturne\n10. Pratiquez 10 min de cohérence cardiaque",
    sleepTip: "Une méta-analyse de 2021 (Irish et al.) portant sur 37 études a montré que l'hygiène du sommeil seule améliore la qualité de 20-30%. Combinée à la TCC-I (restriction + contrôle du stimulus), l'amélioration atteint 70-80%. L'hygiène du sommeil est nécessaire mais pas suffisante.",
    journalPrompt: "Parmi les 15 règles, lesquelles respectez-vous déjà ? Lesquelles vous semblent les plus difficiles à mettre en place ? Choisissez 3 règles non négociables pour les 30 prochains jours.",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 7,
    title: "Jour 7 — Bilan semaine 1 et ajustements",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Première semaine terminée. Aujourd'hui, nous mesurons vos progrès, calculons votre efficacité de sommeil et ajustons votre fenêtre de sommeil si nécessaire. C'est aussi un jour de récupération mentale avant la semaine 2.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Calculez votre efficacité de sommeil de la semaine 1 : (temps dormi / temps au lit) × 100\n2. Si > 85% : augmentez votre fenêtre de 15 min dès demain\n3. Si 80-85% : maintenez la fenêtre actuelle\n4. Si < 80% : réduisez la fenêtre de 15 min (oui, c'est contre-intuitif)\n5. Relisez votre journal de sommeil : identifiez les patterns (jours difficiles, déclencheurs)\n6. Méditez 25 min avec la relaxation profonde\n7. Pratiquez 10 min de cohérence cardiaque\n8. Écrivez votre intention pour la semaine 2",
    sleepTip: "L'efficacité de sommeil est l'indicateur clé de la TCC-I. Un score > 85% est considéré comme excellent. Si votre score est < 80%, réduire davantage votre fenêtre (restriction plus stricte) améliore paradoxalement la qualité en augmentant la pression de sommeil. Faites confiance au processus.",
    journalPrompt: "Quelle est votre efficacité de sommeil de la semaine 1 ? Comment se compare-t-elle à votre baseline du Jour 1 ? Qu'est-ce qui a le plus changé ? Qu'est-ce qui reste difficile ? Quel est votre engagement pour la semaine 2 ?",
    estimatedMinutes: 40,
  },

  // ─── SEMAINE 2 : TCC-I ET RESTRUCTURATION COGNITIVE ───────────────────────
  {
    dayNumber: 8,
    title: "Jour 8 — Pleine conscience et MBSR",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "La pleine conscience (mindfulness) est un pilier de la transformation du sommeil. Aujourd'hui, nous explorons le protocole MBSR (Mindfulness-Based Stress Reduction) adapté au sommeil, avec un focus sur le scan corporel.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Allongez-vous et faites un scan corporel de 20 minutes : observez chaque partie de votre corps sans chercher à changer quoi que ce soit\n2. Commencez par le pied droit : orteils, plante, talon, cheville... remontez jusqu'au sommet du crâne\n3. Si des pensées arrivent, dites mentalement 'je pense' et revenez à la sensation physique\n4. Observez les zones de tension sans jugement : 'Il y a de la tension dans les épaules'\n5. Méditez 20 min avec la méditation de la forêt apaisante\n6. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "Le scan corporel (body scan) est la pratique centrale du MBSR. Une méta-analyse de 2019 (Gong et al.) portant sur 18 études a montré que 8 semaines de MBSR améliorent la qualité du sommeil autant que les somnifères (d = 0.63), réduisent l'insomnie de 50% et diminuent les ruminations nocturnes de 40%.",
    journalPrompt: "Comment s'est passé le scan corporel ? Avez-vous réussi à observer vos sensations sans vous perdre dans les pensées ? Quelles zones de tension avez-vous remarquées ? Vous êtes-vous endormi(e) pendant la pratique ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 9,
    title: "Jour 9 — Gestion des pensées intrusives",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Les pensées intrusives la nuit sont le symptôme principal de l'insomnie. Aujourd'hui, nous explorons 5 techniques avancées pour gérer les ruminations nocturnes : défusion cognitive, intention paradoxale, imagerie mentale, ancrage sensoriel et journaling nocturne.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Technique 1 — Défusion cognitive : observez vos pensées comme des nuages qui passent dans le ciel. Vous êtes le ciel, pas les nuages.\n2. Technique 2 — Intention paradoxale : essayez activement de rester éveillé(e) sans effort. Dites-vous : 'Je vais rester éveillé(e) encore 5 minutes.'\n3. Technique 3 — Imagerie mentale : visualisez un endroit sûr et paisible en détail (plage, forêt, montagne)\n4. Technique 4 — Ancrage sensoriel : concentrez-vous sur 5 choses que vous voyez, 4 que vous entendez, 3 que vous touchez, 2 que vous sentez, 1 que vous goûtez\n5. Technique 5 — Journaling nocturne : notez brièvement vos pensées sur un carnet et dites 'je m'en occupe demain'\n6. Méditez 20 min avec la méditation de la pleine lune\n7. Pratiquez la respiration carrée (4-4-4-4) pendant 5 minutes",
    sleepTip: "La défusion cognitive (ACT — Acceptance and Commitment Therapy) consiste à observer les pensées sans s'y identifier. Au lieu de dire 'Je suis anxieux', dites 'J'observe une pensée anxieuse'. Cette distance cognitive réduit l'activation émotionnelle de 40% selon les études de Hayes & Strosahl.",
    journalPrompt: "Quelle technique avez-vous trouvée la plus efficace pour gérer vos pensées intrusives ? Avez-vous réussi à créer une distance avec vos pensées ? Comment vous êtes-vous senti(e) après ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 10,
    title: "Jour 10 — Respiration avancée et système nerveux",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "La respiration est le seul pont entre votre système nerveux conscient et autonome. Aujourd'hui, nous explorons 4 techniques de respiration avancées pour activer le système parasympathique : cohérence cardiaque, 4-7-8, respiration alternée et respiration carrée.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Technique 1 — Cohérence cardiaque : 10 min de respiration à 5 cycles/min (5 sec inspiration, 5 sec expiration). Utilisez une app pour guider le rythme.\n2. Technique 2 — 4-7-8 : 4 cycles (inspirez 4 sec, retenez 7 sec, expirez 8 sec)\n3. Technique 3 — Respiration alternée (Nadi Shodhana) : bouchez la narine droite, inspirez à gauche, bouchez la gauche, expirez à droite. Alternez pendant 5 min.\n4. Technique 4 — Respiration carrée : 4 sec inspiration, 4 sec rétention, 4 sec expiration, 4 sec rétention. 5 min.\n5. Méditez 20 min avec la méditation de gratitude\n6. Notez 5 choses pour lesquelles vous êtes reconnaissant(e)",
    sleepTip: "La cohérence cardiaque (5 respirations/min pendant 5 min) active le nerf vague et stimule le système parasympathique. En 5 minutes, votre fréquence cardiaque se stabilise, votre tension artérielle baisse et votre cortisol diminue de 23%. Pratiquez 3 fois par jour (matin, midi, soir) pour des effets durables.",
    journalPrompt: "Quelle technique de respiration avez-vous préférée ? Avez-vous remarqué des changements dans votre corps pendant la pratique (chaleur, fourmillements, relaxation) ? Comment vous êtes-vous senti(e) après 10 min de cohérence cardiaque ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 11,
    title: "Jour 11 — Nutrition et sommeil : protocole avancé",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "L'alimentation influence directement la qualité du sommeil via les neurotransmetteurs, le microbiote intestinal et le rythme circadien. Aujourd'hui, nous créons votre protocole nutritionnel personnalisé pour un sommeil optimal.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Dînez au moins 3h avant le coucher (idéalement avant 19h30)\n2. Choisissez un dîner riche en tryptophane : dinde, saumon, œufs, tofu, banane, noix de cajou, graines de courge\n3. Ajoutez des glucides complexes pour faciliter le passage du tryptophane dans le cerveau : riz complet, quinoa, patate douce\n4. Évitez les aliments inflammatoires : sucre raffiné, gluten, produits laitiers (si intolérance)\n5. Suppléments : magnésium glycinate 300mg, vitamine D3 2000 UI, oméga-3 1000mg\n6. Tisane : camomille, passiflore, valériane ou mélisse\n7. Méditez 20 min avec la méditation voyage nocturne\n8. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "Le tryptophane est le précurseur de la sérotonine, qui se convertit en mélatonine la nuit. Mais 95% de la sérotonine est produite dans l'intestin. Un microbiote déséquilibré réduit la production de sérotonine et perturbe le sommeil. Mangez des prébiotiques (ail, oignon, poireau) et des probiotiques (kéfir, kimchi, miso).",
    journalPrompt: "Qu'avez-vous mangé et bu aujourd'hui ? À quelle heure avez-vous dîné ? Avez-vous consommé de la caféine après 14h ou de l'alcool ce soir ? Comment vous sentez-vous physiquement ? Prenez-vous des suppléments ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 12,
    title: "Jour 12 — Gestion des réveils nocturnes avancée",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Les réveils nocturnes sont normaux (4 à 6 micro-réveils par nuit). Le problème, c'est quand ils durent et s'accompagnent d'anxiété. Aujourd'hui, nous explorons un protocole en 7 étapes pour gérer les réveils avec élégance.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Étape 1 : Ne regardez PAS l'heure (retournez votre réveil)\n2. Étape 2 : Pratiquez immédiatement 4 cycles de respiration 4-7-8\n3. Étape 3 : Si des pensées arrivent, notez-les brièvement sur un carnet et dites 'je m'en occupe demain'\n4. Étape 4 : Visualisez un endroit sécurisant pendant 3 minutes\n5. Étape 5 : Si vous êtes encore éveillé(e) après 20 min, levez-vous et lisez dans une autre pièce à faible lumière\n6. Étape 6 : Retournez au lit uniquement quand vous ressentez une somnolence réelle\n7. Étape 7 : Répétez autant de fois que nécessaire\n8. Méditez 20 min avec la relaxation profonde avant le coucher\n9. Pratiquez 10 min de cohérence cardiaque",
    sleepTip: "Regarder l'heure lors d'un réveil nocturne active l'anxiété de performance. Votre cerveau calcule 'il me reste X heures' et libère du cortisol. Une étude de 2018 (Tang et al.) a montré que les personnes qui regardent l'heure lors des réveils ont un temps de rendormissement 2 fois plus long.",
    journalPrompt: "Vous êtes-vous réveillé(e) cette nuit ? Combien de fois ? Avez-vous regardé l'heure ? Qu'avez-vous fait pour vous rendormir ? Avez-vous dû vous lever ? Qu'est-ce qui a fonctionné ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 13,
    title: "Jour 13 — Exercice physique et sommeil",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "L'exercice physique améliore la qualité du sommeil de 65% selon les méta-analyses. Mais le timing, l'intensité et le type d'exercice sont cruciaux. Aujourd'hui, nous créons votre protocole d'exercice optimal pour le sommeil.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "box",
    ambientSound: "rain",
    eveningRoutine: "1. Faites au moins 30 min d'exercice modéré par jour (marche rapide, vélo, natation)\n2. Timing optimal : entre 16h et 19h (augmente la température corporelle, qui baissera au moment du coucher)\n3. Évitez l'exercice intense après 20h (augmente le cortisol et retarde l'endormissement)\n4. Le soir : privilégiez le yoga doux, les étirements ou le tai-chi\n5. Faites 10 min d'étirements doux 1h avant le coucher\n6. Méditez 20 min avec la méditation de la forêt apaisante\n7. Pratiquez la respiration carrée (4-4-4-4) pendant 5 minutes",
    sleepTip: "L'exercice augmente le sommeil profond (stade 3 NREM) de 30 à 40%. Mais l'exercice intense le soir augmente la température corporelle et le cortisol, ce qui retarde l'endormissement de 1 à 2 heures. Une méta-analyse de 2017 (Kredlow et al.) recommande d'éviter l'exercice intense dans les 4 heures avant le coucher.",
    journalPrompt: "Avez-vous fait de l'exercice aujourd'hui ? À quelle heure ? Quel type d'exercice ? Quelle intensité ? Comment vous êtes-vous senti(e) ce soir ? Avez-vous remarqué un impact sur votre sommeil ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 14,
    title: "Jour 14 — Bilan semaine 2 et ajustements",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Deux semaines terminées. Vous avez maintenant des outils puissants de la TCC-I et de la pleine conscience. Aujourd'hui, nous mesurons vos progrès, ajustons votre fenêtre de sommeil et préparons la semaine 3 : les pratiques contemplatives avancées.",
    meditationSlug: "pleine-lune",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Calculez votre efficacité de sommeil de la semaine 2 : (temps dormi / temps au lit) × 100\n2. Si > 85% : augmentez votre fenêtre de 15 min\n3. Si 80-85% : maintenez la fenêtre actuelle\n4. Si < 80% : réduisez la fenêtre de 15 min\n5. Relisez vos 3 croyances négatives reformulées (Jour 5) : y croyez-vous encore ?\n6. Identifiez les 3 techniques qui vous ont le plus aidé cette semaine\n7. Méditez 25 min avec la méditation de la pleine lune\n8. Pratiquez 10 min de cohérence cardiaque\n9. Écrivez votre intention pour la semaine 3",
    sleepTip: "À mi-parcours, la plupart des participants remarquent une amélioration de 40 à 50% de leur qualité de sommeil. Si vos progrès sont plus lents, c'est normal — la transformation du sommeil prend du temps. L'important est la direction, pas la vitesse. Chaque nuit est une nouvelle opportunité.",
    journalPrompt: "Comparez votre sommeil de la semaine 2 à la semaine 1 : efficacité, temps d'endormissement, réveils, qualité ressentie. Qu'est-ce qui a le plus changé ? Qu'est-ce qui reste difficile ? Quel est votre engagement pour la semaine 3 ?",
    estimatedMinutes: 40,
  },

  // ─── SEMAINE 3 : PRATIQUES CONTEMPLATIVES AVANCÉES ────────────────────────
  {
    dayNumber: 15,
    title: "Jour 15 — Yoga nidra : le sommeil yogique",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "Le yoga nidra ('sommeil yogique') est une pratique millénaire qui induit un état de conscience entre l'éveil et le sommeil. 30 minutes de yoga nidra équivalent à 4 heures de sommeil en termes de récupération. Aujourd'hui, nous explorons le protocole complet.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Allongez-vous en savasana (sur le dos, bras le long du corps, paumes vers le haut)\n2. Formulez votre sankalpa (intention) : une phrase courte et positive sur votre sommeil (ex : 'Je m'endors facilement et naturellement')\n3. Rotation de conscience : portez votre attention successivement sur chaque partie du corps (main droite, pouce droit, index droit, majeur...)\n4. Visualisation : imaginez des scènes paisibles (plage, forêt, montagne)\n5. Méditez 25 min avec la méditation voyage nocturne\n6. Répétez votre sankalpa 3 fois mentalement\n7. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "Le yoga nidra active les ondes delta (0.5-4 Hz) caractéristiques du sommeil profond, tout en maintenant une conscience légère. Des études d'IRM fonctionnelle montrent que le yoga nidra régule l'amygdale (centre de la peur) et le cortex préfrontal, réduisant l'hyperactivation nocturne de 50%.",
    journalPrompt: "Quel sankalpa (intention) avez-vous formulé ? Comment s'est passée la rotation de conscience ? Avez-vous réussi à rester conscient(e) tout au long ? Vous êtes-vous endormi(e) ? Comment vous sentez-vous après ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 16,
    title: "Jour 16 — Hypnose et auto-suggestion avancées",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "L'auto-hypnose est une compétence que tout le monde peut apprendre. En état hypnagogique, votre subconscient est particulièrement réceptif aux suggestions positives. Aujourd'hui, nous créons votre script d'auto-hypnose personnalisé et explorons l'induction hypnotique.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Créez votre script d'auto-suggestion (5-7 phrases positives au présent) :\n   - 'Je m'endors facilement et naturellement'\n   - 'Mon sommeil est profond et réparateur'\n   - 'Je me réveille reposé(e) et plein(e) d'énergie'\n   - 'Mon corps sait comment dormir'\n   - 'Je fais confiance à mon corps'\n2. Allongez-vous et induisez un état de relaxation profonde (10 min de respiration lente)\n3. Répétez mentalement votre script 5 fois, lentement, en visualisant chaque affirmation\n4. Méditez 25 min avec la relaxation profonde\n5. Pratiquez 10 min de cohérence cardiaque\n6. Répétez votre script une dernière fois avant de vous endormir",
    sleepTip: "L'état hypnagogique (transition éveil-sommeil) est caractérisé par des ondes thêta et une suggestibilité accrue. Des études montrent que les suggestions positives répétées dans cet état modifient les croyances inconscientes sur le sommeil en 2 à 3 semaines. C'est le principe de l'auto-hypnose d'Émile Coué, validé par les neurosciences modernes.",
    journalPrompt: "Quelles affirmations avez-vous choisies pour votre script ? Comment vous êtes-vous senti(e) en les répétant ? Avez-vous remarqué une résistance intérieure ? Comment s'est passée votre nuit ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 17,
    title: "Jour 17 — Méditation de dissolution des frontières",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La méditation de dissolution des frontières (issue du yoga nidra et du bouddhisme tibétain) active les ondes thêta caractéristiques de l'état hypnagogique. En pratiquant régulièrement, vous apprenez à 'surfer' sur cet état et à glisser naturellement dans le sommeil.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Allongez-vous dans votre position de sommeil préférée\n2. Fermez les yeux et imaginez que les frontières de votre corps se dissolvent progressivement\n3. Sentez-vous devenir de plus en plus léger(ère), comme si vous flottiez\n4. Laissez votre conscience se diffuser dans l'espace autour de vous\n5. Imaginez que vous vous fondez dans le matelas, dans la pièce, dans l'univers\n6. Méditez 25 min avec la méditation de la forêt apaisante\n7. Pratiquez 4 cycles de respiration 4-7-8 en fin de méditation",
    sleepTip: "La méditation de dissolution des frontières active les ondes thêta (4-8 Hz) caractéristiques de l'état hypnagogique — la transition entre l'éveil et le sommeil. En pratiquant régulièrement, vous apprenez à 'surfer' sur cet état et à glisser naturellement dans le sommeil. C'est la pratique préférée des méditants avancés.",
    journalPrompt: "Comment s'est passée la méditation de dissolution des frontières ? Avez-vous réussi à sentir vos frontières corporelles se dissoudre ? Avez-vous eu des images ou des sensations particulières ? Vous êtes-vous endormi(e) pendant la méditation ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 18,
    title: "Jour 18 — Visualisation créatrice et imagerie mentale",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La visualisation créatrice est une technique puissante pour reprogrammer le subconscient. Aujourd'hui, nous créons votre 'film mental' du sommeil idéal — une séquence d'images détaillées que vous visualiserez chaque soir pour conditionner votre cerveau.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "rain",
    eveningRoutine: "1. Créez votre 'film mental' du sommeil idéal (5-7 scènes) :\n   - Scène 1 : Vous préparez votre chambre (obscurité, fraîcheur, silence)\n   - Scène 2 : Vous faites votre rituel du soir (tisane, méditation, respiration)\n   - Scène 3 : Vous vous allongez dans votre lit confortable\n   - Scène 4 : Vous sentez votre corps se détendre progressivement\n   - Scène 5 : Vous glissez naturellement dans le sommeil\n   - Scène 6 : Vous dormez profondément toute la nuit\n   - Scène 7 : Vous vous réveillez reposé(e) et plein(e) d'énergie\n2. Visualisez ce film en détail pendant 10 minutes\n3. Méditez 25 min avec la méditation de la pleine lune\n4. Pratiquez la respiration carrée (4-4-4-4) pendant 5 minutes\n5. Visualisez à nouveau votre film mental avant de vous endormir",
    sleepTip: "La visualisation créatrice active les mêmes zones cérébrales que l'expérience réelle. En visualisant votre sommeil idéal chaque soir, vous créez des connexions neuronales qui facilitent l'endormissement. Les athlètes olympiques utilisent cette technique pour améliorer leurs performances de 20 à 30%.",
    journalPrompt: "Décrivez votre 'film mental' du sommeil idéal. Quelles scènes avez-vous choisies ? Comment vous êtes-vous senti(e) en les visualisant ? Avez-vous remarqué un impact sur votre sommeil ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 19,
    title: "Jour 19 — Méditation de la montagne",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La méditation de la montagne est une pratique de stabilité et d'ancrage. Vous devenez une montagne immobile et imperturbable, quelles que soient les pensées et émotions qui traversent votre esprit. C'est une pratique puissante pour l'insomnie chronique.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Asseyez-vous ou allongez-vous confortablement\n2. Imaginez que vous êtes une montagne majestueuse : stable, immobile, inébranlable\n3. Votre base est profondément ancrée dans la terre\n4. Les pensées et émotions sont comme des nuages qui passent autour de la montagne\n5. Les nuages vont et viennent, mais la montagne reste immobile\n6. Vous êtes la montagne, pas les nuages\n7. Méditez 25 min avec la méditation de gratitude\n8. Notez 5 choses pour lesquelles vous êtes reconnaissant(e)\n9. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "La méditation de la montagne (issue du MBSR de Jon Kabat-Zinn) développe l'équanimité — la capacité à rester stable face aux expériences difficiles. Pour l'insomnie, cette équanimité est cruciale : au lieu de lutter contre l'éveil, vous l'observez avec bienveillance. Cette acceptation paradoxale déclenche souvent l'endormissement.",
    journalPrompt: "Comment s'est passée la méditation de la montagne ? Avez-vous réussi à rester stable comme une montagne ? Quels 'nuages' (pensées/émotions) sont passés ? Comment avez-vous réagi ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 20,
    title: "Jour 20 — Pratique de la gratitude et psychologie positive",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La gratitude est l'émotion la plus puissante pour le sommeil. Des études montrent que 15 minutes de journaling de gratitude avant le coucher améliorent la qualité du sommeil de 25% et réduisent le temps d'endormissement de 30%. Aujourd'hui, nous créons votre rituel de gratitude.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Écrivez 5 choses pour lesquelles vous êtes reconnaissant(e) aujourd'hui (soyez spécifique)\n2. Pour chaque chose, écrivez POURQUOI vous êtes reconnaissant(e) (pas juste 'ma famille', mais 'ma fille qui m'a fait rire ce matin')\n3. Relisez votre liste à voix haute\n4. Fermez les yeux et ressentez la gratitude dans votre corps (chaleur dans la poitrine, sourire)\n5. Méditez 25 min avec la méditation voyage nocturne\n6. Pratiquez 10 min de cohérence cardiaque\n7. Visualisez une scène de gratitude avant de vous endormir",
    sleepTip: "La gratitude active le cortex préfrontal ventromédian et libère de la dopamine et de la sérotonine. Une étude de 2011 (Wood et al.) a montré que les personnes qui pratiquent le journaling de gratitude 15 min avant le coucher dorment 30 min de plus et ont un sommeil de meilleure qualité. La gratitude est l'antidote à l'anxiété.",
    journalPrompt: "Quelles sont les 5 choses pour lesquelles vous êtes reconnaissant(e) aujourd'hui ? Comment vous êtes-vous senti(e) en écrivant et en relisant votre liste ? Avez-vous remarqué un impact sur votre humeur et votre sommeil ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 21,
    title: "Jour 21 — Bilan semaine 3 et préparation semaine 4",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "Trois semaines terminées. Vous avez maintenant un arsenal de pratiques contemplatives avancées. Aujourd'hui, nous mesurons vos progrès, identifions vos pratiques préférées et préparons la semaine 4 : l'intégration et la maîtrise.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Calculez votre efficacité de sommeil de la semaine 3 : (temps dormi / temps au lit) × 100\n2. Si > 85% : augmentez votre fenêtre de 15 min\n3. Si 80-85% : maintenez la fenêtre actuelle\n4. Si < 80% : maintenez la restriction stricte une semaine de plus\n5. Identifiez vos 3 pratiques contemplatives préférées (celles que vous continuerez après le programme)\n6. Méditez 30 min avec la relaxation profonde\n7. Pratiquez 10 min de cohérence cardiaque\n8. Écrivez votre intention pour la semaine 4",
    sleepTip: "À 3 semaines, la plupart des participants remarquent une amélioration de 50 à 60% de leur qualité de sommeil. Les connexions neuronales commencent à se consolider. Continuez votre pratique pendant 45 jours supplémentaires pour ancrer définitivement vos nouvelles habitudes.",
    journalPrompt: "Comparez votre sommeil de la semaine 3 aux semaines 1 et 2 : efficacité, temps d'endormissement, réveils, qualité ressentie. Quelles sont vos 3 pratiques contemplatives préférées ? Pourquoi ? Quel est votre engagement pour la semaine 4 ?",
    estimatedMinutes: 40,
  },

  // ─── SEMAINE 4 : INTÉGRATION ET MAÎTRISE ──────────────────────────────────
  {
    dayNumber: 22,
    title: "Jour 22 — Ancrage des habitudes et habit stacking",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Vous êtes à 8 jours de la fin. Vos nouvelles habitudes sont en train de s'ancrer neurologiquement. Aujourd'hui, nous utilisons les techniques de 'habit stacking' (empilement d'habitudes) pour rendre votre rituel du soir automatique et durable.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Identifiez votre 'habitude ancre' du soir (quelque chose que vous faites déjà : brosser les dents, préparer votre tasse de tisane...)\n2. Attachez votre rituel du sommeil à cette habitude ancre\n3. Exemple : 'Après avoir brossé les dents, je fais 5 min de respiration, puis je médite 20 min'\n4. Créez une checklist visuelle de votre rituel et affichez-la dans votre chambre\n5. Méditez 25 min avec la méditation de la forêt apaisante\n6. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "Le 'habit stacking' (James Clear, Atomic Habits) consiste à attacher une nouvelle habitude à une habitude existante. La formule est : 'Après [habitude existante], je ferai [nouvelle habitude]'. Cette technique exploite les circuits neuronaux déjà formés pour créer de nouvelles connexions plus rapidement.",
    journalPrompt: "Quelle est votre habitude ancre du soir ? Comment avez-vous attaché votre rituel à cette habitude ? Depuis combien de jours votre rituel du soir est-il devenu automatique ? Que ressentez-vous quand vous ne le faites pas ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 23,
    title: "Jour 23 — Gestion des rechutes et plan de maintenance",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Les mauvaises nuits font partie du processus. Même après 23 jours de transformation, vous aurez des nuits difficiles. Aujourd'hui, nous créons votre 'plan de rechute' et votre 'plan de maintenance' pour ne pas perdre vos acquis.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Écrivez votre 'plan de rechute' : que ferez-vous lors d'une mauvaise nuit ?\n   - Ne pas paniquer : une mauvaise nuit ne détruit pas 23 jours de progrès\n   - Maintenir les horaires le lendemain matin (même si fatigué(e))\n   - Identifier le déclencheur (stress, repas tardif, écrans...)\n   - Reprendre le protocole dès le soir suivant\n   - Relire son journal de sommeil pour se rappeler des progrès\n2. Écrivez votre 'plan de maintenance' : comment maintiendrez-vous vos acquis après le Jour 30 ?\n3. Méditez 25 min avec la méditation de la pleine lune\n4. Pratiquez la respiration carrée (4-4-4-4) pendant 5 minutes",
    sleepTip: "La rechute est une étape normale du changement de comportement (modèle de Prochaska). 90% des personnes qui transforment leur sommeil connaissent au moins une semaine difficile dans les 3 premiers mois. La clé est de ne pas catastrophiser : une mauvaise nuit n'efface pas les progrès neurologiques déjà réalisés.",
    journalPrompt: "Avez-vous déjà eu des mauvaises nuits depuis le début du programme ? Comment avez-vous réagi ? Qu'est-ce qui vous a aidé à vous en remettre ? Quel est votre plan de rechute désormais ? Quel est votre plan de maintenance ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 24,
    title: "Jour 24 — Votre programme personnalisé pour la vie",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Aujourd'hui, vous créez votre programme de sommeil personnalisé pour les prochains mois et années — adapté à votre chronotype, vos contraintes et vos pratiques préférées. C'est votre guide pour maintenir vos acquis à vie.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Rédigez votre 'Programme de sommeil personnalisé' :\n   - Heure de coucher et de lever fixées (même le week-end)\n   - Votre rituel du soir en 20-30 min (listez les étapes)\n   - Votre technique de respiration préférée\n   - Votre méditation préférée\n   - Vos 3 règles d'hygiène du sommeil non négociables\n   - Votre plan de rechute\n   - Votre plan de maintenance\n2. Méditez 25 min avec la méditation de gratitude\n3. Notez 5 choses pour lesquelles vous êtes reconnaissant(e)\n4. Pratiquez 4 cycles de respiration 4-7-8\n5. Relisez votre programme et visualisez-vous le suivre dans 6 mois",
    sleepTip: "La personnalisation est la clé de la durabilité. Un programme de sommeil qui ne correspond pas à votre style de vie sera abandonné en 2 semaines. Votre programme idéal est celui que vous pouvez maintenir 80% du temps, même en voyage, même lors de semaines chargées. Visez la régularité, pas la perfection.",
    journalPrompt: "Décrivez votre programme de sommeil personnalisé. Quelles sont vos 3 pratiques non négociables ? Comment allez-vous maintenir ces habitudes lors des vacances, des voyages ou des semaines difficiles ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 25,
    title: "Jour 25 — Sommeil et relations : le couple",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Votre partenaire influence directement votre sommeil. Aujourd'hui, nous explorons les stratégies pour optimiser le sommeil en couple : synchronisation des horaires, gestion des ronflements, température de la chambre et communication.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Discutez avec votre partenaire de vos horaires de sommeil respectifs\n2. Si vos chronotypes sont très différents, envisagez des chambres séparées (ce n'est pas un échec, c'est de l'optimisation)\n3. Si votre partenaire ronfle, utilisez des bouchons d'oreilles ou du bruit blanc\n4. Trouvez un compromis sur la température de la chambre (idéalement 16-19°C)\n5. Créez un rituel du soir commun (tisane, méditation, gratitude)\n6. Méditez 25 min avec la méditation voyage nocturne\n7. Pratiquez 10 min de cohérence cardiaque",
    sleepTip: "Une étude de 2013 (Troxel et al.) a montré que les couples qui dorment ensemble ont un sommeil de moins bonne qualité (plus de réveils, moins de sommeil profond) que ceux qui dorment séparément. Si votre sommeil est sévèrement perturbé par votre partenaire, envisagez des chambres séparées. C'est un choix d'optimisation, pas un problème relationnel.",
    journalPrompt: "Votre partenaire influence-t-il votre sommeil ? Comment ? Avez-vous discuté de vos horaires et de vos besoins respectifs ? Quelles solutions avez-vous trouvées ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 26,
    title: "Jour 26 — Sommeil et voyages : maintenir la routine",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Les voyages perturbent le sommeil (jet lag, nouvel environnement, stress). Aujourd'hui, nous créons votre 'kit de voyage du sommeil' — un ensemble de stratégies pour maintenir votre routine même en déplacement.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Créez votre 'kit de voyage du sommeil' :\n   - Masque de sommeil\n   - Bouchons d'oreilles ou écouteurs avec bruit blanc\n   - Tisane en sachet (camomille, valériane)\n   - Huile essentielle de lavande\n   - Application de méditation sur votre téléphone\n   - Votre rituel du soir simplifié (15 min)\n2. Stratégie jet lag : exposez-vous à la lumière du matin à destination, évitez la lumière le soir\n3. Méditez 25 min avec la relaxation profonde\n4. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "Le jet lag est causé par un décalage entre votre horloge biologique et l'heure locale. La règle générale : il faut 1 jour d'adaptation par heure de décalage. Pour accélérer l'adaptation, exposez-vous à 10 000 lux de lumière le matin à destination et évitez la lumière le soir. La mélatonine 0.5mg peut aider.",
    journalPrompt: "Voyagez-vous souvent ? Comment les voyages affectent-ils votre sommeil ? Qu'allez-vous mettre dans votre 'kit de voyage du sommeil' ? Comment allez-vous maintenir votre rituel en déplacement ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 27,
    title: "Jour 27 — Sommeil et stress chronique : outils avancés",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Le stress chronique est l'ennemi numéro 1 du sommeil. Aujourd'hui, nous explorons des outils avancés de gestion du stress : cohérence cardiaque 3 fois par jour, journaling structuré, technique du 'worry time' et méditation de compassion.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Pratiquez la cohérence cardiaque 3 fois par jour : matin (réveil), midi (pause déjeuner), soir (avant le coucher)\n2. Technique du 'worry time' : réservez 20 min à 18h pour vous inquiéter activement. Notez toutes vos inquiétudes. Quand une pensée anxieuse survient au lit, dites : 'Je me suis déjà occupé de ça à 18h.'\n3. Journaling structuré : écrivez pendant 10 min sur votre journée (ce qui s'est bien passé, ce qui a été difficile, ce que vous avez appris)\n4. Méditez 25 min avec la méditation de la forêt apaisante\n5. Pratiquez 10 min de cohérence cardiaque",
    sleepTip: "Le stress chronique active l'axe hypothalamo-hypophyso-surrénalien (HHS) et libère du cortisol, ce qui maintient l'éveil. La cohérence cardiaque 3 fois par jour réduit le cortisol de 23% et améliore la variabilité de la fréquence cardiaque (VFC), un marqueur de la résilience au stress.",
    journalPrompt: "Quel est votre niveau de stress actuellement (1-10) ? Quelles sont vos 3 principales sources de stress ? Avez-vous pratiqué la cohérence cardiaque 3 fois aujourd'hui ? Comment vous êtes-vous senti(e) ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 28,
    title: "Jour 28 — Bilan semaine 4 et préparation finale",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Quatre semaines terminées. Vous êtes à 2 jours de la fin. Aujourd'hui, nous mesurons vos progrès finaux, calculons votre score ISI et préparons votre célébration du Jour 30.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Calculez votre efficacité de sommeil de la semaine 4 : (temps dormi / temps au lit) × 100\n2. Remplissez le questionnaire ISI (Insomnia Severity Index) et comparez votre score au Jour 1\n3. Identifiez les 3 changements les plus importants dans votre vie depuis 28 jours\n4. Préparez votre célébration du Jour 30 : comment allez-vous marquer cette étape ?\n5. Méditez 30 min avec la méditation de la pleine lune\n6. Pratiquez la respiration carrée (4-4-4-4) pendant 5 minutes\n7. Écrivez une lettre à votre futur vous dans 6 mois : rappels, encouragements, engagements",
    sleepTip: "À 4 semaines, la plupart des participants remarquent une amélioration de 60 à 70% de leur qualité de sommeil. Les connexions neuronales sont maintenant bien établies. Continuez votre pratique pendant 45 jours supplémentaires pour consolider définitivement vos acquis.",
    journalPrompt: "Comparez votre sommeil de la semaine 4 aux semaines 1, 2 et 3 : efficacité, temps d'endormissement, réveils, qualité ressentie. Quel est votre score ISI final ? Comment se compare-t-il au Jour 1 ? Qu'est-ce qui a le plus changé ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 29,
    title: "Jour 29 — Consolidation et révision",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Avant-dernier jour. Aujourd'hui est un jour de consolidation et de révision. Nous relisons votre journal de sommeil depuis le Jour 1, identifions les patterns et célébrons vos progrès. Demain sera le jour de la célébration finale.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Relisez votre journal de sommeil depuis le Jour 1 : mesurez vos progrès\n2. Identifiez les patterns : quels jours ont été les plus difficiles ? Quels déclencheurs ?\n3. Identifiez les victoires : quels jours ont été les meilleurs ? Qu'avez-vous fait différemment ?\n4. Calculez votre efficacité de sommeil moyenne des 30 jours et comparez-la à votre baseline du Jour 1\n5. Méditez 30 min avec la méditation de gratitude\n6. Notez 10 choses pour lesquelles vous êtes reconnaissant(e) dans ce parcours\n7. Pratiquez 4 cycles de respiration 4-7-8",
    sleepTip: "La consolidation est cruciale pour l'apprentissage. En relisant votre journal de sommeil, vous identifiez les patterns invisibles au quotidien. Ces insights vous permettront de maintenir vos acquis à long terme et de réagir rapidement en cas de rechute.",
    journalPrompt: "Quels sont les 3 patterns les plus importants que vous avez identifiés dans votre journal de sommeil ? Quelles sont vos 3 plus grandes victoires ? Qu'est-ce qui vous rend le plus fier(ère) ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 30,
    title: "Jour 30 — Célébration et engagement à vie",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Vous avez fait 30 jours ! C'est une transformation réelle et profonde — votre cerveau a créé de nouvelles connexions neuronales, votre horloge biologique est synchronisée et vous avez des outils pour la vie. Aujourd'hui est un jour de célébration et d'engagement à vie.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Relisez votre journal de sommeil depuis le Jour 1 : mesurez vos progrès\n2. Calculez votre efficacité de sommeil finale et comparez-la au Jour 1\n3. Calculez votre score ISI final et comparez-le au Jour 1\n4. Identifiez les 5 changements les plus importants dans votre vie depuis 30 jours\n5. Écrivez une lettre à votre futur vous dans 1 an : rappels, encouragements, engagements\n6. Méditez 30 min avec la relaxation profonde guidée\n7. Pratiquez 10 min de cohérence cardiaque\n8. Célébrez ! Vous méritez cette fierté. Vous êtes maintenant un maître du sommeil.",
    sleepTip: "30 jours est un jalon important, mais la maîtrise du sommeil est un processus continu. Les habitudes complexes prennent 66 jours en moyenne pour devenir automatiques. Continuez votre programme pendant 36 jours supplémentaires pour consolider définitivement vos acquis. Vous avez tous les outils. Faites-vous confiance.",
    journalPrompt: "Comparez votre sommeil du Jour 30 au Jour 1 : efficacité, temps d'endormissement, réveils, qualité ressentie, énergie dans la journée, humeur. Qu'est-ce qui a le plus changé ? Quel est votre engagement pour les 6 prochains mois ? Comment allez-vous célébrer cette victoire ?",
    estimatedMinutes: 45,
  },
];

async function seed() {
  console.log("🌟 Seeding programme Maître du sommeil (30 jours)...\n");

  let success = 0;
  let errors = 0;

  for (const day of MAITRE_DAYS) {
    try {
      await db.insert(programDays).values({
        ...day,
        programSlug: "maitre-sommeil",
      }).onDuplicateKeyUpdate({
        set: {
          title: day.title,
          theme: day.theme,
          description: day.description,
          meditationSlug: day.meditationSlug,
          breathingExercise: day.breathingExercise,
          ambientSound: day.ambientSound,
          eveningRoutine: day.eveningRoutine,
          sleepTip: day.sleepTip,
          journalPrompt: day.journalPrompt,
          estimatedMinutes: day.estimatedMinutes,
        },
      });
      console.log(`✅ Jour ${day.dayNumber} — ${day.title}`);
      success++;
    } catch (e) {
      console.error(`❌ Erreur Jour ${day.dayNumber}:`, e);
      errors++;
    }
  }

  console.log(`\n🎉 Terminé ! ${success} jours insérés, ${errors} erreurs.`);
  process.exit(0);
}

seed().catch(console.error);
