/**
 * Script de seed enrichi — Programmes 21j et 30j
 * Contenu unique et varié pour chaque jour
 * Exécuter avec : npx tsx scripts/seed-programs-enriched.ts
 */
import "../scripts/load-env.js";
import { drizzle } from "drizzle-orm/mysql2";
import { programDays } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

// ─── Programme "Transformation du sommeil" — 21 jours ─────────────────────────

const TRANSFORMATION_DAYS = [
  // ═══════════════════════════════════════════════════════
  // SEMAINE 1 : FONDATIONS
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 1,
    title: "Jour 1 — Évaluation et fondations",
    theme: "Semaine 1 : Fondations",
    description: "Bienvenue dans votre transformation de 21 jours. Aujourd'hui, nous posons un diagnostic précis de votre sommeil actuel et établissons vos objectifs personnels. Cette évaluation initiale sera votre point de référence pour mesurer vos progrès.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Remplissez votre journal de sommeil initial (heure coucher habituelle, durée, qualité)\n2. Éteignez tous les écrans 90 min avant le coucher\n3. Préparez votre chambre : température 17-19°C, obscurité totale\n4. Méditez 15 min avec la méditation guidée\n5. Pratiquez 4 cycles de respiration 4-7-8\n6. Notez 3 intentions pour ce programme",
    sleepTip: "La première étape d'une transformation durable est l'observation sans jugement. Pendant cette semaine, tenez un journal de sommeil : heure de coucher, heure de lever, nombre de réveils, qualité ressentie sur 10. Ces données vous révèleront des patterns invisibles à l'œil nu.",
    journalPrompt: "Décrivez votre sommeil idéal en détail. À quelle heure vous endormez-vous ? Combien d'heures dormez-vous ? Comment vous sentez-vous au réveil ? Qu'est-ce qui vous empêche d'atteindre ce sommeil idéal ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 2,
    title: "Jour 2 — Hygiène du sommeil avancée",
    theme: "Semaine 1 : Fondations",
    description: "L'hygiène du sommeil va bien au-delà d'éteindre les écrans. Aujourd'hui, nous explorons les 12 règles d'or du sommeil validées par la science, et vous identifiez lesquelles vous ne respectez pas encore.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Vérifiez les 12 règles d'hygiène du sommeil (liste dans le journal)\n2. Prenez un bain chaud 90 min avant le coucher (la chute de température corporelle favorise l'endormissement)\n3. Portez des chaussettes chaudes si vous avez les pieds froids\n4. Méditez avec la relaxation musculaire progressive\n5. Pratiquez 5 min de cohérence cardiaque (5s inspir / 5s expir)\n6. Lisez un livre physique pendant 20 min",
    sleepTip: "La température corporelle est le chef d'orchestre du sommeil. Elle doit baisser de 1°C pour déclencher l'endormissement. Un bain chaud 90 min avant le coucher provoque une vasodilatation qui accélère cette chute thermique. Gardez votre chambre entre 16 et 19°C pour maintenir cette température idéale toute la nuit.",
    journalPrompt: "Parmi les 12 règles d'hygiène du sommeil, lesquelles respectez-vous déjà ? Lesquelles sont les plus difficiles à appliquer pour vous ? Pourquoi ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 3,
    title: "Jour 3 — Gestion du stress nocturne",
    theme: "Semaine 1 : Fondations",
    description: "Le stress est le principal saboteur du sommeil. Aujourd'hui, nous explorons le mécanisme cortisol-mélatonine et apprenons à désamorcer le stress avant qu'il n'envahisse vos nuits.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Faites une 'vidange mentale' : écrivez toutes vos inquiétudes sur papier, puis fermez le carnet\n2. Pratiquez la technique du 'worry time' : 15 min dédiées aux soucis, puis stop\n3. Faites 10 min de yoga doux ou d'étirements\n4. Méditez avec la méditation de la forêt apaisante\n5. Pratiquez 4 cycles de 4-7-8\n6. Visualisez votre lieu sûr pendant 5 min",
    sleepTip: "Le cortisol (hormone du stress) et la mélatonine (hormone du sommeil) sont en opposition directe. Quand l'un monte, l'autre baisse. La technique du 'worry time' consiste à planifier délibérément 15-20 minutes dans l'après-midi pour ruminer vos soucis. En leur donnant un espace dédié, vous empêchez leur invasion nocturne.",
    journalPrompt: "Quelles sont les 3 sources de stress qui perturbent le plus votre sommeil ? Pour chacune, existe-t-il une action concrète que vous pouvez prendre demain ? Notez-la.",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 4,
    title: "Jour 4 — Respiration et système nerveux",
    theme: "Semaine 1 : Fondations",
    description: "Votre respiration est la télécommande de votre système nerveux. Aujourd'hui, nous explorons en profondeur le lien entre respiration, nerf vague et qualité du sommeil.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "rain",
    eveningRoutine: "1. Pratiquez 5 min de respiration diaphragmatique (main sur le ventre)\n2. Essayez la respiration carrée : 4s inspir, 4s pause, 4s expir, 4s pause — 8 cycles\n3. Faites un scan corporel de 10 min (attention aux zones de tension)\n4. Méditez avec la méditation de la pleine lune\n5. Endormez-vous en respirant lentement : 4s inspir, 6s expir",
    sleepTip: "Le nerf vague est le câble de communication entre votre cerveau et vos organes. Une respiration lente (6 respirations/minute) stimule ce nerf et active le système parasympathique — votre mode 'repos et digestion'. L'expiration longue est la clé : elle doit toujours être plus longue que l'inspiration pour maximiser l'effet calmant.",
    journalPrompt: "Comment respirez-vous habituellement ? Plutôt par le ventre ou par la poitrine ? Avez-vous remarqué des changements dans votre état mental après les exercices de respiration d'aujourd'hui ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 5,
    title: "Jour 5 — Alimentation, lumière et sommeil",
    theme: "Semaine 1 : Fondations",
    description: "Ce que vous mangez et la lumière à laquelle vous vous exposez influencent directement votre production de mélatonine. Aujourd'hui, nous optimisons ces deux leviers souvent négligés.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Dînez léger (évitez les graisses et sucres rapides après 19h)\n2. Buvez une tisane de camomille, valériane ou ashwagandha\n3. Tamisez les lumières de votre maison dès 20h (lumières ambrées uniquement)\n4. Méditez avec la méditation de gratitude\n5. Pratiquez 5 min de cohérence cardiaque\n6. Notez 5 choses pour lesquelles vous êtes reconnaissant aujourd'hui",
    sleepTip: "La lumière bleue (écrans, LED blanches) bloque la mélatonine pendant 2-3h. Mais la lumière ambrée (bougies, ampoules orange) n'a aucun effet sur la mélatonine. Investissez dans des ampoules à spectre chaud (2700K) pour votre chambre et salon. Le tryptophane (banane, dinde, noix, fromage) est le précurseur de la mélatonine — consommez-en au dîner.",
    journalPrompt: "Décrivez votre alimentation d'aujourd'hui. Avez-vous consommé de la caféine ? De l'alcool ? À quelle heure ? Comment vous sentez-vous ce soir par rapport aux soirs précédents ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 6,
    title: "Jour 6 — Optimiser l'environnement du sommeil",
    theme: "Semaine 1 : Fondations",
    description: "Votre chambre doit être un sanctuaire dédié exclusivement au sommeil et à l'intimité. Aujourd'hui, nous passons en revue chaque élément de votre environnement nocturne.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Audit de votre chambre : température, lumière, bruit, literie, odeurs\n2. Installez un diffuseur de lavande ou de bois de santal\n3. Vérifiez que votre matelas et oreiller soutiennent correctement votre corps\n4. Méditez avec la méditation du voyage nocturne\n5. Pratiquez 4 cycles de 4-7-8\n6. Couchez-vous uniquement quand vous ressentez de la somnolence",
    sleepTip: "Le contrôle du stimulus est une technique de TCC-I (Thérapie Cognitive et Comportementale pour l'Insomnie) : votre lit doit être associé uniquement au sommeil. Si vous lisez, regardez la TV ou travaillez au lit, votre cerveau associe ce lieu à l'éveil. Règle d'or : si vous n'êtes pas endormi en 20 minutes, levez-vous et allez dans une autre pièce.",
    journalPrompt: "Décrivez votre chambre idéale pour dormir. Qu'est-ce qui est déjà optimal ? Qu'est-ce qui pourrait être amélioré ? Quels changements allez-vous faire cette semaine ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 7,
    title: "Jour 7 — Bilan semaine 1 et consolidation",
    theme: "Semaine 1 : Fondations",
    description: "Félicitations pour votre première semaine ! Aujourd'hui, nous faisons un bilan complet de vos progrès, identifions vos points forts et préparons la semaine 2 qui sera plus intensive.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Relisez votre journal de la semaine 1\n2. Calculez votre efficacité de sommeil : (temps dormi / temps au lit) × 100\n3. Identifiez les 3 pratiques les plus efficaces pour vous\n4. Méditez avec la relaxation profonde\n5. Pratiquez 5 min de cohérence cardiaque\n6. Écrivez votre bilan et vos intentions pour la semaine 2",
    sleepTip: "L'efficacité de sommeil est le meilleur indicateur de qualité : un bon dormeur passe 85% ou plus de son temps au lit à dormir. Si votre efficacité est inférieure à 85%, la restriction du sommeil (technique TCC-I) sera votre outil principal en semaine 2. Ne vous découragez pas — c'est normal en début de programme.",
    journalPrompt: "Quel est votre bilan de la semaine 1 ? Quelle a été votre plus grande découverte sur votre sommeil ? Quelle pratique a eu le plus d'impact ? Quel est votre objectif principal pour la semaine 2 ?",
    estimatedMinutes: 35,
  },

  // ═══════════════════════════════════════════════════════
  // SEMAINE 2 : APPROFONDISSEMENT (TCC-I)
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 8,
    title: "Jour 8 — TCC-I : La restriction du sommeil",
    theme: "Semaine 2 : Approfondissement",
    description: "La restriction du sommeil est la technique la plus efficace de la TCC-I, avec un taux de succès de 80%. Elle est contre-intuitive mais puissante : on réduit temporairement le temps au lit pour créer une pression de sommeil qui améliore la qualité.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Calculez votre fenêtre de sommeil : heure de lever fixe - votre temps de sommeil réel\n2. Ne vous couchez pas avant l'heure calculée, même si vous êtes fatigué\n3. Levez-vous à la même heure chaque matin, même le week-end\n4. Méditez avec la méditation de la forêt\n5. Pratiquez 4 cycles de 4-7-8 au coucher\n6. Si vous ne dormez pas en 20 min, levez-vous et revenez quand vous êtes somnolent",
    sleepTip: "La restriction du sommeil fonctionne en augmentant l'adénosine — la molécule de la fatigue — dans votre cerveau. Plus elle s'accumule, plus l'endormissement est rapide et le sommeil profond. Après 1-2 semaines, vous augmentez progressivement votre fenêtre de sommeil de 15 min quand votre efficacité dépasse 85%.",
    journalPrompt: "Quelle est votre fenêtre de sommeil calculée ? Comment vous sentez-vous avec cette restriction ? Notez votre heure de coucher, heure de lever et estimation du temps dormi.",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 9,
    title: "Jour 9 — Contrôle du stimulus",
    theme: "Semaine 2 : Approfondissement",
    description: "Votre cerveau a peut-être associé votre lit à l'éveil et à l'anxiété. Aujourd'hui, nous reconstruisons l'association lit = sommeil grâce aux techniques de contrôle du stimulus.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Réservez votre lit exclusivement au sommeil (plus de téléphone, TV, lecture au lit)\n2. Allez au lit uniquement quand vous ressentez de la somnolence (yeux lourds, bâillements)\n3. Si vous êtes éveillé plus de 20 min, levez-vous et faites une activité calme\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez la respiration carrée (4-4-4-4) × 8 cycles\n6. Répétez autant de fois que nécessaire — la régularité crée le conditionnement",
    sleepTip: "Le conditionnement classique (comme Pavlov) s'applique au sommeil. Si vous passez des heures éveillé dans votre lit, votre cerveau apprend que le lit = éveil. En ne restant au lit que lorsque vous dormez, vous recréez l'association lit = sommeil en 2-3 semaines. C'est inconfortable au début, mais transformateur.",
    journalPrompt: "Avez-vous eu à vous lever la nuit dernière ? Combien de fois ? Comment vous êtes-vous senti ? Notez les pensées qui vous ont traversé l'esprit pendant ces moments d'éveil.",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 10,
    title: "Jour 10 — Restructuration cognitive",
    theme: "Semaine 2 : Approfondissement",
    description: "Vos pensées sur le sommeil influencent directement votre capacité à dormir. Aujourd'hui, nous identifions et transformons les croyances dysfonctionnelles qui alimentent l'insomnie.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Identifiez une pensée négative sur votre sommeil (ex: 'Je ne dormirai jamais bien')\n2. Questionnez-la : Est-ce vraiment vrai ? Quelles preuves ? Quelle pensée alternative ?\n3. Remplacez-la par une pensée réaliste et apaisante\n4. Méditez avec la méditation de gratitude\n5. Pratiquez 5 min de cohérence cardiaque\n6. Notez 3 preuves que votre sommeil s'améliore",
    sleepTip: "Les catastrophisations nocturnes ('Si je ne dors pas, je serai inutile demain') amplifient l'anxiété et empêchent le sommeil. La technique ABC de la TCC : A (Activating event = ne pas dormir), B (Belief = pensée catastrophiste), C (Consequence = anxiété). Modifier B change C. Remplacez 'Je dois absolument dormir' par 'Se reposer au lit est déjà bénéfique'.",
    journalPrompt: "Quelles sont vos 3 croyances les plus négatives sur votre sommeil ? Pour chacune, écrivez une pensée alternative plus réaliste et bienveillante. Comment vous sentez-vous après cet exercice ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 11,
    title: "Jour 11 — Pleine conscience nocturne",
    theme: "Semaine 2 : Approfondissement",
    description: "La pleine conscience transforme votre relation au sommeil. Au lieu de lutter contre l'éveil, vous apprenez à l'observer avec curiosité et bienveillance. Cette acceptation paradoxale favorise l'endormissement.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Pratiquez 10 min de méditation de pleine conscience assise\n2. Observez vos pensées sans les juger : 'Je remarque que je pense à...'\n3. Faites un scan corporel de 15 min en pleine conscience\n4. Méditez avec la méditation du voyage nocturne\n5. Pratiquez 4 cycles de 4-7-8\n6. Au lit, observez les sensations de votre corps sans chercher à dormir",
    sleepTip: "La pleine conscience du sommeil (mindful sleep) consiste à observer l'expérience d'être allongé sans chercher à dormir. Paradoxalement, cette acceptation réduit l'anxiété de performance et facilite l'endormissement. Dites-vous : 'Je me repose, c'est déjà excellent. Le sommeil viendra naturellement.' Cette attitude réduit le temps d'endormissement de 40%.",
    journalPrompt: "Qu'avez-vous observé pendant la méditation de pleine conscience ? Quelles pensées sont apparues ? Comment avez-vous réagi à ces pensées ? Avez-vous réussi à les observer sans vous y identifier ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 12,
    title: "Jour 12 — Gestion des réveils nocturnes",
    theme: "Semaine 2 : Approfondissement",
    description: "Se réveiller la nuit est normal — nous avons tous 4 à 6 micro-réveils par nuit. Le problème est quand on n'arrive pas à se rendormir. Aujourd'hui, nous apprenons les stratégies pour gérer ces réveils.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Préparez un 'kit de réveil nocturne' : carnet, stylo, tisane froide\n2. Si vous vous réveillez, ne regardez pas l'heure (couvrez votre réveil)\n3. Pratiquez la technique du 'body scan' pour vous rendormir\n4. Méditez avec la relaxation profonde\n5. Pratiquez la respiration carrée × 6 cycles\n6. Si vous êtes éveillé plus de 30 min, levez-vous et lisez dans une lumière tamisée",
    sleepTip: "Regarder l'heure lors d'un réveil nocturne est une des pires choses à faire : cela active le cortex préfrontal (calcul, planification) et rend le rendormissement difficile. Couvrez votre réveil ou retournez-le. Si vous vous réveillez, dites-vous : 'Je suis dans mon lit, en sécurité, au chaud. Mon corps se repose même si mon esprit est actif.'",
    journalPrompt: "Combien de fois vous êtes-vous réveillé cette nuit ? À quelle heure ? Qu'avez-vous fait ? Quelle stratégie a fonctionné pour vous rendormir ? Laquelle n'a pas fonctionné ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 13,
    title: "Jour 13 — Chronobiologie personnelle",
    theme: "Semaine 2 : Approfondissement",
    description: "Êtes-vous un lève-tôt ou un couche-tard ? Votre chronotype est inscrit dans vos gènes. Aujourd'hui, nous découvrons votre chronotype et adaptons votre programme en conséquence.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Faites le test du chronotype (questionnaire de Munich dans votre journal)\n2. Identifiez votre 'fenêtre de sommeil naturelle' (2h avant et après votre heure de sommeil idéale)\n3. Exposez-vous à la lumière vive dès le matin pour synchroniser votre horloge\n4. Méditez avec la méditation de la forêt\n5. Pratiquez 5 min de cohérence cardiaque\n6. Couchez-vous à l'heure correspondant à votre chronotype",
    sleepTip: "Il existe 3 chronotypes : les lions (lève-tôt, 25%), les ours (milieu, 50%) et les loups (couche-tard, 25%). Forcer un loup à dormir à 22h est aussi inefficace que forcer un lion à dormir à minuit. La génétique détermine 50% de votre chronotype. Adaptez votre horaire de sommeil à votre biologie plutôt que de lutter contre elle.",
    journalPrompt: "Quel est votre chronotype naturel ? À quelle heure vous endormez-vous naturellement quand vous n'avez pas de contraintes ? À quelle heure vous réveillez-vous spontanément ? Comment votre vie actuelle est-elle alignée (ou non) avec votre chronotype ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 14,
    title: "Jour 14 — Bilan semaine 2 et ajustements",
    theme: "Semaine 2 : Approfondissement",
    description: "Deux semaines de transformation ! Aujourd'hui, nous analysons vos données de sommeil, mesurons vos progrès et ajustons votre programme pour la semaine finale de consolidation.",
    meditationSlug: "pleine-lune",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Calculez votre efficacité de sommeil moyenne sur les 7 derniers jours\n2. Si > 85% : augmentez votre fenêtre de sommeil de 15 min\n3. Si < 85% : maintenez la restriction actuelle\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez 4 cycles de 4-7-8\n6. Écrivez votre bilan détaillé et vos objectifs pour la semaine 3",
    sleepTip: "Après 2 semaines de TCC-I, la plupart des personnes voient leur efficacité de sommeil augmenter de 15 à 25 points. Si vous n'avez pas encore de résultats significatifs, c'est normal — certains ont besoin de 3-4 semaines. La clé est la constance : ne sautez pas de jours, même le week-end.",
    journalPrompt: "Comparez votre sommeil de la semaine 2 à la semaine 1. Qu'est-ce qui a changé ? Quelle technique a eu le plus d'impact ? Qu'est-ce qui reste difficile ? Quel est votre plan pour la semaine 3 ?",
    estimatedMinutes: 35,
  },

  // ═══════════════════════════════════════════════════════
  // SEMAINE 3 : CONSOLIDATION
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 15,
    title: "Jour 15 — Méditation avancée du sommeil",
    theme: "Semaine 3 : Consolidation",
    description: "Vous avez posé des fondations solides. En semaine 3, nous approfondissons les pratiques contemplatives pour ancrer durablement votre transformation. Aujourd'hui : la méditation du sommeil avancée.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Créez un espace de méditation dédié dans votre chambre\n2. Méditez 20 min avec la méditation de gratitude nocturne\n3. Pratiquez la visualisation créatrice : imaginez votre nuit idéale en détail\n4. Pratiquez 5 min de cohérence cardiaque\n5. Utilisez des mantras du sommeil : 'Je lâche prise, je me laisse aller au sommeil'\n6. Endormez-vous en répétant mentalement votre mantra",
    sleepTip: "La visualisation créatrice active les mêmes zones cérébrales que l'expérience réelle. En imaginant une nuit de sommeil parfaite — vous vous endormez facilement, vous dormez profondément, vous vous réveillez reposé — vous créez un 'script neuronal' que votre cerveau cherchera à reproduire. Pratiquez cette visualisation chaque soir pendant 5 minutes.",
    journalPrompt: "Comment était votre méditation ce soir ? Avez-vous réussi à visualiser votre nuit idéale ? Quelles émotions avez-vous ressenties ? Votre mantra vous a-t-il aidé à vous endormir ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 16,
    title: "Jour 16 — Yoga Nidra : le sommeil yogique",
    theme: "Semaine 3 : Consolidation",
    description: "Le Yoga Nidra est une technique de relaxation profonde qui induit un état entre veille et sommeil. Une session de 30 minutes équivaut à 2-3 heures de sommeil en termes de récupération. Aujourd'hui, nous l'intégrons à votre pratique.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Allongez-vous confortablement, couverture légère\n2. Pratiquez 20 min de Yoga Nidra (rotation de conscience corps)\n3. Restez immobile même si vous vous endormez\n4. Après la session, notez vos sensations dans le journal\n5. Pratiquez 4 cycles de 4-7-8\n6. Endormez-vous en maintenant l'état de relaxation profonde",
    sleepTip: "Le Yoga Nidra induit l'état hypnagogique — la frontière entre veille et sommeil — caractérisé par des ondes thêta (4-8 Hz). Dans cet état, le cerveau est extrêmement réceptif aux suggestions positives et aux reprogrammations. C'est pourquoi les affirmations prononcées pendant le Yoga Nidra ont un effet profond et durable sur les habitudes de sommeil.",
    journalPrompt: "Comment s'est passée votre première session de Yoga Nidra ? Avez-vous réussi à rester éveillé ou vous êtes-vous endormi ? Quelles sensations avez-vous remarquées dans votre corps ? Comment vous sentez-vous après ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 17,
    title: "Jour 17 — Auto-hypnose et suggestion",
    theme: "Semaine 3 : Consolidation",
    description: "L'auto-hypnose est un outil puissant pour reprogrammer les patterns de sommeil au niveau inconscient. Aujourd'hui, nous apprenons les bases de l'auto-hypnose appliquée au sommeil.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "box",
    ambientSound: "forest",
    eveningRoutine: "1. Installez-vous confortablement, yeux fermés\n2. Comptez à rebours de 10 à 1 en vous approfondissant à chaque chiffre\n3. Visualisez un escalier qui descend vers un lieu de paix totale\n4. Répétez 3 fois votre suggestion : 'Je m'endors facilement et naturellement'\n5. Méditez avec la méditation du voyage nocturne\n6. Pratiquez la respiration carrée × 6 cycles avant de dormir",
    sleepTip: "L'état hypnotique léger (état alpha, 8-12 Hz) est naturellement atteint deux fois par jour : juste avant de s'endormir et juste après le réveil. C'est le moment idéal pour les suggestions positives. Profitez de ces moments pour répéter mentalement vos affirmations de sommeil. Votre cerveau est alors 10 fois plus réceptif qu'en état d'éveil normal.",
    journalPrompt: "Avez-vous réussi à entrer dans un état de relaxation profonde ? Quelles suggestions avez-vous utilisées ? Comment vous êtes-vous senti pendant et après ? Avez-vous remarqué des différences dans votre endormissement ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 18,
    title: "Jour 18 — Gestion des rechutes",
    theme: "Semaine 3 : Consolidation",
    description: "Les mauvaises nuits font partie du processus. Aujourd'hui, nous développons votre plan de résilience pour les périodes difficiles, afin que les rechutes ne deviennent pas des régressions.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Identifiez vos 3 principaux déclencheurs de mauvaises nuits\n2. Pour chaque déclencheur, définissez un plan d'action concret\n3. Créez votre 'boîte à outils de crise' : liste de techniques qui fonctionnent pour vous\n4. Méditez avec la méditation de la forêt\n5. Pratiquez 5 min de cohérence cardiaque\n6. Relisez votre boîte à outils avant de dormir",
    sleepTip: "Une mauvaise nuit n'efface pas 17 jours de progrès. Le cerveau retient les nouvelles habitudes même après une rechute. La clé est de ne pas catastrophiser : 'J'ai eu une mauvaise nuit, c'est normal, je reprends ma routine demain.' Les rechutes sont des données, pas des échecs. Chaque difficulté surmontée renforce votre résilience.",
    journalPrompt: "Quels sont vos déclencheurs de mauvaises nuits (stress, voyage, conflit, maladie) ? Pour chacun, quelle est votre stratégie de gestion ? Qu'avez-vous appris sur vous-même au cours de ces 18 jours ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 19,
    title: "Jour 19 — Ancrage des habitudes",
    theme: "Semaine 3 : Consolidation",
    description: "Après 21 jours, les nouvelles habitudes commencent à s'ancrer neurologiquement. Aujourd'hui, nous utilisons la science de la formation des habitudes pour rendre votre rituel du sommeil automatique et durable.",
    meditationSlug: "pleine-lune",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Identifiez le 'déclencheur' de votre rituel du soir (ex: brosser les dents)\n2. Enchaînez vos pratiques dans un ordre fixe et immuable\n3. Célébrez chaque étape complétée (petite récompense mentale)\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez 4 cycles de 4-7-8\n6. Notez votre rituel complet dans le journal pour le rendre concret",
    sleepTip: "La formation d'une habitude suit la boucle : déclencheur → routine → récompense. Pour ancrer votre rituel du sommeil, associez-le à un déclencheur existant (brosser les dents, éteindre les lumières) et célébrez chaque soir que vous le complétez. La dopamine libérée lors de la récompense grave l'habitude dans le striatum — le centre des habitudes automatiques.",
    journalPrompt: "Quel est votre rituel du soir actuel, étape par étape ? Quel est votre déclencheur ? Quelle est votre récompense ? Comment vous sentez-vous quand vous complétez votre rituel ?",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 20,
    title: "Jour 20 — Votre programme personnalisé",
    theme: "Semaine 3 : Consolidation",
    description: "Vous avez exploré de nombreuses techniques. Aujourd'hui, vous créez votre programme personnalisé — une synthèse unique des pratiques les plus efficaces pour vous, que vous pourrez maintenir indéfiniment.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Listez toutes les techniques que vous avez essayées\n2. Notez chacune sur 10 (efficacité pour vous personnellement)\n3. Sélectionnez vos 5-7 pratiques préférées\n4. Créez votre rituel du soir personnalisé en 20-30 min\n5. Méditez avec la méditation de gratitude\n6. Écrivez votre programme personnalisé dans le journal",
    sleepTip: "Le meilleur programme de sommeil est celui que vous maintiendrez. La personnalisation est la clé de la durabilité. Certains préfèrent la cohérence cardiaque, d'autres le Yoga Nidra ou la méditation guidée. Il n'y a pas de programme universel — il y a votre programme, adapté à votre biologie, votre style de vie et vos préférences.",
    journalPrompt: "Quelles sont les 5 pratiques les plus efficaces pour vous ? Décrivez votre programme personnalisé idéal. Comment allez-vous l'intégrer dans votre vie quotidienne sur le long terme ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 21,
    title: "Jour 21 — Célébration et engagement durable",
    theme: "Semaine 3 : Consolidation",
    description: "Vous avez terminé les 21 jours de transformation ! Aujourd'hui est un jour de célébration, de gratitude et d'engagement envers votre nouveau moi qui dort bien. Vous avez accompli quelque chose d'extraordinaire.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Relisez l'intégralité de votre journal de 21 jours\n2. Comparez votre sommeil du jour 1 et du jour 21\n3. Célébrez vos progrès : offrez-vous quelque chose de symbolique\n4. Méditez avec la méditation du voyage nocturne\n5. Pratiquez la respiration carrée × 8 cycles\n6. Écrivez une lettre à votre futur vous dans 6 mois sur votre sommeil",
    sleepTip: "Après 21 jours, votre cerveau a créé de nouvelles connexions neuronales. Mais les habitudes se consolident vraiment en 66 jours (pas 21 — c'est un mythe). Continuez votre rituel pendant encore 45 jours pour ancrer définitivement ces changements. La rechute est possible, mais vous avez maintenant tous les outils pour vous relever rapidement.",
    journalPrompt: "Comparez votre sommeil du jour 1 et aujourd'hui. Qu'est-ce qui a le plus changé ? De quoi êtes-vous le plus fier ? Quel engagement prenez-vous pour maintenir ces habitudes ? Écrivez une lettre à votre futur vous dans 6 mois.",
    estimatedMinutes: 40,
  },
];

// ─── Programme "Maître du sommeil" — 30 jours ─────────────────────────────────

const MAITRE_DAYS = [
  // ═══════════════════════════════════════════════════════
  // SEMAINE 1 : DIAGNOSTIC ET FONDATIONS AVANCÉES
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 1,
    title: "Jour 1 — Diagnostic expert du sommeil",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Bienvenue dans le programme expert. Ce programme est conçu pour ceux qui veulent une maîtrise totale de leur sommeil. Aujourd'hui, nous réalisons un diagnostic complet incluant votre architecture de sommeil, vos cycles et vos facteurs de risque.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Complétez le questionnaire de diagnostic complet (Pittsburgh Sleep Quality Index)\n2. Notez votre architecture de sommeil estimée : cycles, phases, réveils\n3. Identifiez vos 5 principaux facteurs de risque\n4. Méditez 20 min avec la méditation guidée\n5. Pratiquez 5 cycles de 4-7-8\n6. Définissez vos 3 objectifs principaux pour ce programme",
    sleepTip: "L'architecture du sommeil se compose de cycles de 90 minutes, chacun incluant sommeil léger, sommeil profond et sommeil paradoxal (REM). Un adulte a besoin de 4 à 6 cycles complets. Le sommeil profond (N3) est dominant en première moitié de nuit, le sommeil paradoxal en seconde moitié. Perturber la fin de nuit coupe le sommeil REM, essentiel pour la mémoire et la régulation émotionnelle.",
    journalPrompt: "Décrivez votre architecture de sommeil typique. Combien de cycles estimez-vous faire ? À quel moment de la nuit vous réveillez-vous le plus souvent ? Qu'est-ce que cela vous dit sur votre sommeil ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 2,
    title: "Jour 2 — Neurosciences du sommeil",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Comprendre le 'pourquoi' du sommeil transforme votre motivation. Aujourd'hui, nous explorons ce que la science moderne sait sur les fonctions du sommeil : nettoyage cérébral, consolidation mémorielle, régulation émotionnelle.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Lisez 15 min sur les neurosciences du sommeil (résumé dans le journal)\n2. Pratiquez la relaxation musculaire progressive avancée (20 min)\n3. Méditez avec la relaxation profonde\n4. Pratiquez 5 min de cohérence cardiaque\n5. Avant de dormir, dites-vous : 'Mon cerveau va se nettoyer et consolider mes apprentissages cette nuit'\n6. Notez ce que vous voulez que votre cerveau consolide pendant votre sommeil",
    sleepTip: "Le système glymphatique est le système de nettoyage du cerveau, actif uniquement pendant le sommeil profond. Il élimine les déchets métaboliques, dont la protéine bêta-amyloïde (liée à Alzheimer). Une nuit de sommeil insuffisant augmente de 30% la concentration de ces protéines toxiques. Dormir n'est pas du temps perdu — c'est de la maintenance cérébrale essentielle.",
    journalPrompt: "Qu'avez-vous appris sur les fonctions du sommeil qui vous a le plus surpris ? Comment cette connaissance change-t-elle votre rapport au sommeil ? Qu'est-ce qui vous motive le plus à bien dormir ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 3,
    title: "Jour 3 — Protocole anti-cortisol",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Le cortisol chroniquement élevé est l'ennemi numéro 1 du sommeil profond. Aujourd'hui, nous mettons en place un protocole complet pour réguler votre axe HPA (hypothalamo-hypophyso-surrénalien).",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Évitez tout exercice intense après 18h (augmente le cortisol)\n2. Pratiquez la technique de décompression du soir : 20 min de transition active-passive\n3. Faites 15 min de yoga restauratif (postures douces)\n4. Méditez avec la méditation de la forêt\n5. Pratiquez 5 cycles de 4-7-8\n6. Prenez un supplément de magnésium glycinate (200-400mg) si vous en avez",
    sleepTip: "Le cortisol suit un rythme circadien naturel : pic au réveil (aide à se lever), déclin progressif jusqu'au soir. Le stress chronique perturbe ce rythme et maintient le cortisol élevé la nuit. L'ashwagandha (adaptogène) réduit le cortisol nocturne de 27% selon des études cliniques. La phosphatidylsérine (200mg) est également efficace pour abaisser le cortisol post-exercice.",
    journalPrompt: "Évaluez votre niveau de stress chronique sur 10. Quelles sont les principales sources de stress dans votre vie ? Quelles stratégies de gestion du stress utilisez-vous déjà ? Lesquelles voulez-vous développer ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 4,
    title: "Jour 4 — Optimisation circadienne avancée",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Votre horloge biologique maîtresse (noyau suprachiasmatique) synchronise tous vos rythmes physiologiques. Aujourd'hui, nous apprenons à l'optimiser avec précision.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "rain",
    eveningRoutine: "1. Exposez-vous à la lumière vive (10 000 lux) dès le réveil (10-15 min)\n2. Mangez à des horaires réguliers (les repas synchronisent les horloges périphériques)\n3. Évitez la lumière bleue dès 20h (lunettes ou filtres)\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez la respiration carrée × 8 cycles\n6. Couchez-vous à la même heure exacte, même le week-end",
    sleepTip: "Votre corps possède des milliers d'horloges biologiques dans chaque organe, toutes synchronisées par l'horloge maîtresse. La lumière est le synchroniseur principal (zeitgeber), mais les repas, l'exercice et la température jouent aussi un rôle. Manger à des heures irrégulières désynchronise les horloges périphériques et perturbe le sommeil, même si vous vous couchez à heure fixe.",
    journalPrompt: "À quelle heure mangez-vous habituellement ? Vos horaires de repas sont-ils réguliers ? Comment la lumière influence-t-elle votre énergie au cours de la journée ? Avez-vous essayé la luminothérapie matinale ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 5,
    title: "Jour 5 — Nutrition avancée pour le sommeil",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "La nutrition du sommeil va bien au-delà d'éviter la caféine. Aujourd'hui, nous explorons les nutriments, compléments et timing alimentaire qui optimisent chaque phase de votre sommeil.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Dînez avec des aliments riches en tryptophane et glucides complexes\n2. Prenez vos compléments du soir : magnésium, L-théanine, mélatonine si nécessaire\n3. Buvez une tisane de valériane + passiflore + mélisse\n4. Méditez avec la méditation de gratitude\n5. Pratiquez 5 min de cohérence cardiaque\n6. Notez votre alimentation du jour et son impact sur votre énergie",
    sleepTip: "Les compléments les plus validés scientifiquement pour le sommeil : Magnésium glycinate (400mg) — améliore le sommeil profond. L-théanine (200mg) — réduit l'anxiété sans sédation. Mélatonine (0,5-1mg) — efficace pour le décalage horaire et les troubles circadiens, pas pour l'insomnie chronique. Ashwagandha (600mg) — réduit le cortisol et améliore la qualité globale. Consultez un médecin avant de commencer.",
    journalPrompt: "Quels compléments avez-vous essayés pour le sommeil ? Avec quels résultats ? Qu'est-ce que vous mangez habituellement le soir ? Comment votre alimentation influence-t-elle votre sommeil ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 6,
    title: "Jour 6 — Exercice physique et sommeil",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "L'exercice est l'un des meilleurs somnifères naturels — mais le timing est crucial. Aujourd'hui, nous optimisons votre activité physique pour maximiser son impact sur votre sommeil.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "ocean",
    eveningRoutine: "1. Si vous avez fait du sport aujourd'hui, prenez une douche froide pour abaisser la température\n2. Faites 15 min de yoga restauratif ou d'étirements doux\n3. Méditez avec la méditation du voyage nocturne\n4. Pratiquez 5 cycles de 4-7-8\n5. Notez votre activité physique du jour et son impact sur votre fatigue\n6. Planifiez votre exercice de demain avant 17h",
    sleepTip: "L'exercice aérobique modéré (30 min, 5 jours/semaine) améliore la qualité du sommeil de 65% et réduit le temps d'endormissement de 55%. Mais l'exercice intense après 18h augmente le cortisol et la température corporelle, retardant l'endormissement de 1-2h. Idéal : exercice le matin ou en début d'après-midi. La marche de 20 min après le dîner améliore la glycémie et favorise l'endormissement.",
    journalPrompt: "Quelle est votre activité physique actuelle ? À quelle heure faites-vous du sport ? Comment cela influence-t-il votre sommeil ? Quel changement allez-vous faire pour optimiser le timing de votre exercice ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 7,
    title: "Jour 7 — Bilan semaine 1 et plan d'action",
    theme: "Semaine 1 : Diagnostic et fondations avancées",
    description: "Une semaine de fondations avancées ! Aujourd'hui, nous analysons vos données, mesurons vos progrès initiaux et construisons votre plan d'action personnalisé pour les 3 semaines suivantes.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Calculez votre score PSQI (Pittsburgh Sleep Quality Index) actuel\n2. Comparez avec votre score initial du jour 1\n3. Identifiez vos 3 leviers d'amélioration prioritaires\n4. Méditez avec la relaxation profonde\n5. Pratiquez 5 min de cohérence cardiaque\n6. Écrivez votre plan d'action pour les semaines 2, 3 et 4",
    sleepTip: "Le score PSQI (0-21) mesure 7 composantes du sommeil : qualité subjective, latence, durée, efficacité, perturbations, médicaments, fonctionnement diurne. Un score > 5 indique un sommeil de mauvaise qualité. La plupart des participants à ce programme voient leur score baisser de 3-5 points en 4 semaines. Chaque point gagné représente une amélioration mesurable de votre santé.",
    journalPrompt: "Quel est votre score PSQI actuel ? Comment se compare-t-il à votre score initial ? Quels sont vos 3 leviers d'amélioration prioritaires ? Quel est votre engagement pour les 3 prochaines semaines ?",
    estimatedMinutes: 40,
  },

  // ═══════════════════════════════════════════════════════
  // SEMAINE 2 : TCC-I ET RESTRUCTURATION COGNITIVE
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 8,
    title: "Jour 8 — TCC-I avancée : protocole complet",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "La TCC-I (Thérapie Cognitive et Comportementale pour l'Insomnie) est reconnue comme le traitement de première ligne par l'American Academy of Sleep Medicine. Aujourd'hui, nous déployons le protocole complet.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Appliquez la restriction du sommeil : calculez votre fenêtre de sommeil\n2. Appliquez le contrôle du stimulus : lit = sommeil uniquement\n3. Méditez avec la méditation de la forêt\n4. Pratiquez 5 cycles de 4-7-8\n5. Si éveillé > 20 min, levez-vous et lisez dans une lumière tamisée\n6. Notez l'heure de coucher, les réveils et l'heure de lever",
    sleepTip: "La TCC-I produit des résultats supérieurs aux somnifères à long terme, sans effets secondaires ni dépendance. Une méta-analyse de 87 études montre que 70-80% des insomniaques chroniques améliorent significativement leur sommeil avec la TCC-I. Les effets sont durables : 85% maintiennent leurs gains à 12 mois, contre 30% pour les somnifères.",
    journalPrompt: "Comment vous sentez-vous avec la restriction du sommeil ? Avez-vous eu des difficultés à rester éveillé jusqu'à votre heure de coucher ? Notez votre heure de coucher, vos réveils et votre heure de lever.",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 9,
    title: "Jour 9 — Thérapie d'acceptation et d'engagement",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "L'ACT (Acceptance and Commitment Therapy) appliquée au sommeil vous apprend à accepter les nuits difficiles sans les amplifier. Aujourd'hui, nous explorons la flexibilité psychologique face à l'insomnie.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Pratiquez la défusion cognitive : observez vos pensées comme des nuages\n2. Identifiez vos valeurs liées au sommeil (santé, énergie, présence)\n3. Méditez avec la méditation de la pleine lune\n4. Pratiquez la respiration carrée × 8 cycles\n5. Pratiquez l'acceptation : 'Cette nuit sera ce qu'elle sera, et c'est acceptable'\n6. Engagez-vous dans une action alignée avec vos valeurs demain, quelle que soit la nuit",
    sleepTip: "L'ACT propose une alternative à la lutte contre l'insomnie : l'acceptation active. Au lieu de 'Je dois dormir', adoptez 'Je peux me reposer et accepter ce qui vient'. Cette flexibilité psychologique réduit l'hyperactivation cognitive — le principal maintien de l'insomnie chronique. L'ACT-I (ACT pour l'insomnie) montre des résultats comparables à la TCC-I classique.",
    journalPrompt: "Comment réagissez-vous habituellement quand vous ne dormez pas ? Quelle est votre relation à l'insomnie ? Pouvez-vous imaginer accepter une mauvaise nuit sans catastrophiser ? Qu'est-ce que cela changerait ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 10,
    title: "Jour 10 — Restructuration des croyances profondes",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Certaines croyances sur le sommeil sont si profondément ancrées qu'elles résistent aux techniques superficielles. Aujourd'hui, nous travaillons sur les schémas cognitifs profonds liés au sommeil.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Identifiez votre croyance centrale sur le sommeil (ex: 'Je suis un mauvais dormeur')\n2. Tracez son origine : d'où vient-elle ? Quand a-t-elle commencé ?\n3. Questionnez-la avec les 4 questions de Byron Katie\n4. Méditez avec la méditation de gratitude\n5. Pratiquez 5 min de cohérence cardiaque\n6. Écrivez votre nouvelle croyance centrale sur le sommeil",
    sleepTip: "Les 4 questions de Byron Katie appliquées au sommeil : 1) 'Je suis un mauvais dormeur' — est-ce vraiment vrai ? 2) Pouvez-vous en être absolument certain ? 3) Comment vous sentez-vous quand vous croyez cette pensée ? 4) Qui seriez-vous sans cette pensée ? Puis inversez : 'Je suis un bon dormeur' — trouvez 3 preuves concrètes.",
    journalPrompt: "Quelle est votre croyance centrale sur votre sommeil ? D'où vient-elle ? Appliquez les 4 questions de Byron Katie. Quelle est votre nouvelle croyance ? Comment vous sentez-vous avec cette nouvelle perspective ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 11,
    title: "Jour 11 — Gestion de l'hyperactivation",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "L'hyperactivation cognitive et physiologique est le mécanisme central de l'insomnie chronique. Aujourd'hui, nous apprenons à la reconnaître et à la désamorcer avec des techniques avancées.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Pratiquez la technique de 'déactivation progressive' : 2h avant le coucher, réduisez progressivement toute stimulation\n2. Faites 20 min de relaxation musculaire progressive profonde\n3. Méditez avec la méditation du voyage nocturne\n4. Pratiquez 5 cycles de 4-7-8\n5. Utilisez la technique du 'cooling down' cognitif : écrivez vos pensées, puis fermez le carnet\n6. Endormez-vous en maintenant votre attention sur votre respiration",
    sleepTip: "L'hyperactivation se manifeste sur 3 niveaux : cognitif (pensées qui s'emballent), physiologique (rythme cardiaque élevé, tension musculaire) et émotionnel (anxiété, frustration). Pour la désamorcer, il faut agir sur les 3 niveaux simultanément : respiration (physiologique), pleine conscience (cognitif) et acceptation (émotionnel). La relaxation musculaire progressive est particulièrement efficace sur le niveau physiologique.",
    journalPrompt: "Sur quel niveau l'hyperactivation est-elle la plus forte pour vous : cognitif, physiologique ou émotionnel ? Quelles techniques fonctionnent le mieux pour chaque niveau ? Comment vous sentez-vous après la relaxation musculaire progressive ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 12,
    title: "Jour 12 — Protocole de gestion des ruminations",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Les ruminations nocturnes — ces pensées qui tournent en boucle — sont l'une des causes les plus fréquentes d'insomnie. Aujourd'hui, nous déployons un protocole complet pour les interrompre.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Pratiquez le 'scheduled worry time' : 20 min à 17h pour ruminer délibérément\n2. Utilisez la technique du 'stop' : quand une rumination apparaît, dites mentalement 'STOP'\n3. Redirigez vers une image mentale apaisante préparée à l'avance\n4. Méditez avec la relaxation profonde\n5. Pratiquez la respiration carrée × 8 cycles\n6. Si des ruminations apparaissent au lit, notez-les sur papier et dites 'je m'en occupe demain'",
    sleepTip: "Les ruminations nocturnes sont souvent des problèmes non résolus qui cherchent une solution. La technique du 'worry time' leur donne un espace dédié dans la journée, réduisant leur invasion nocturne de 50%. Complétez avec la technique du 'worry tree' : ce problème est-il sous mon contrôle ? Si oui, quelle action puis-je prendre ? Si non, puis-je l'accepter ?",
    journalPrompt: "Quelles sont vos ruminations nocturnes les plus fréquentes ? Pour chacune, appliquez le 'worry tree' : est-ce sous votre contrôle ? Quelle action pouvez-vous prendre ? Comment vous sentez-vous après cet exercice ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 13,
    title: "Jour 13 — Techniques de distraction cognitive",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Parfois, la meilleure stratégie n'est pas de combattre les pensées mais de les détourner. Aujourd'hui, nous explorons les techniques de distraction cognitive validées pour l'insomnie.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Préparez votre 'histoire de sommeil' : une histoire imaginaire détaillée et apaisante\n2. Pratiquez la technique du 'comptage des moutons' avancée : comptez à rebours de 300 par 3\n3. Méditez avec la méditation de la forêt\n4. Pratiquez 5 min de cohérence cardiaque\n5. Utilisez la technique du 'body tour' : visitez mentalement chaque partie de votre corps\n6. Endormez-vous en racontant mentalement votre histoire de sommeil",
    sleepTip: "La technique du 'cognitive shuffle' (Dr Luc Beaulieu) consiste à imaginer des séquences d'images aléatoires et sans lien logique (une banane, un château, une chaussette...). Cette randomisation empêche le cerveau de construire des pensées cohérentes et l'amène naturellement vers l'état hypnagogique. C'est l'une des techniques les plus efficaces pour les cerveaux très actifs.",
    journalPrompt: "Quelle technique de distraction cognitive avez-vous essayée ce soir ? A-t-elle fonctionné ? Avez-vous réussi à créer votre histoire de sommeil ? Décrivez-la brièvement.",
    estimatedMinutes: 25,
  },
  {
    dayNumber: 14,
    title: "Jour 14 — Bilan semaine 2 et ajustement du protocole",
    theme: "Semaine 2 : TCC-I et restructuration cognitive",
    description: "Deux semaines de programme expert ! Aujourd'hui, nous analysons vos progrès en profondeur, ajustons votre protocole TCC-I et préparons la semaine 3 de pratiques contemplatives avancées.",
    meditationSlug: "pleine-lune",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Calculez votre efficacité de sommeil moyenne sur 7 jours\n2. Ajustez votre fenêtre de sommeil selon les résultats\n3. Évaluez chaque technique TCC-I sur 10 (efficacité pour vous)\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez 5 cycles de 4-7-8\n6. Écrivez votre bilan et planifiez la semaine 3",
    sleepTip: "À mi-parcours, la plupart des participants voient leur efficacité de sommeil augmenter de 10-20 points et leur temps d'endormissement diminuer de 30-50%. Si vos progrès sont plus lents, c'est souvent dû à une application inconstante des techniques. La TCC-I demande une pratique quotidienne rigoureuse pendant 4-6 semaines pour des résultats optimaux.",
    journalPrompt: "Quel est votre bilan de la semaine 2 ? Votre efficacité de sommeil a-t-elle augmenté ? Quelles techniques TCC-I ont été les plus efficaces ? Qu'est-ce qui reste difficile ? Comment allez-vous ajuster votre approche ?",
    estimatedMinutes: 40,
  },

  // ═══════════════════════════════════════════════════════
  // SEMAINE 3 : PRATIQUES CONTEMPLATIVES AVANCÉES
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 15,
    title: "Jour 15 — Yoga Nidra avancé",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "Le Yoga Nidra avancé va au-delà de la relaxation — il induit des états de conscience modifiés qui permettent une reprogrammation profonde des patterns de sommeil. Aujourd'hui, nous approfondissons cette pratique.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Préparez votre sankalpa (intention profonde) pour la session\n2. Pratiquez 30 min de Yoga Nidra avancé avec rotation de conscience\n3. Restez dans l'état hypnagogique aussi longtemps que possible\n4. Pratiquez 5 min de cohérence cardiaque\n5. Notez vos expériences et visions dans le journal immédiatement après\n6. Endormez-vous en maintenant l'état de conscience élargie",
    sleepTip: "Le Yoga Nidra avancé inclut la pratique du sankalpa — une intention courte, positive et au présent (ex: 'Je dors profondément et me réveille reposé'). Répétée 3 fois en début et fin de session, dans l'état hypnagogique, cette intention s'ancre dans le subconscient avec une efficacité 10 fois supérieure à l'état d'éveil normal. Choisissez un sankalpa qui vous touche profondément.",
    journalPrompt: "Quel est votre sankalpa pour ce programme ? Comment s'est passée votre session de Yoga Nidra avancé ? Avez-vous eu des visions ou des expériences particulières ? Comment vous sentez-vous après ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 16,
    title: "Jour 16 — Méditation Vipassana du sommeil",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La méditation Vipassana (vision pénétrante) appliquée au sommeil vous permet d'observer l'impermanence des états d'éveil et de sommeil, réduisant l'attachement aux résultats et l'anxiété de performance.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Méditez 20 min en Vipassana : observez les sensations corporelles sans réagir\n2. Observez l'impermanence : chaque sensation, pensée, état change constamment\n3. Appliquez cette observation à votre état de sommeil : 'Cet éveil est impermanent'\n4. Pratiquez 5 cycles de 4-7-8\n5. Endormez-vous en observant le passage de l'éveil au sommeil avec curiosité\n6. Notez vos observations dans le journal au réveil",
    sleepTip: "La méditation Vipassana révèle que l'éveil et le sommeil ne sont pas des états fixes mais des processus fluides. En observant ce flux sans s'y attacher, vous réduisez l'anxiété de 'devoir dormir'. Les méditants expérimentés rapportent que la frontière entre veille et sommeil devient floue — ils restent conscients tout en dormant, ce qui élimine la peur de l'insomnie.",
    journalPrompt: "Avez-vous réussi à observer vos sensations sans réagir ? Avez-vous remarqué le moment de transition entre l'éveil et le sommeil ? Qu'avez-vous observé ? Comment cette pratique influence-t-elle votre rapport à l'insomnie ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 17,
    title: "Jour 17 — Hypnose ericksonienne du sommeil",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "L'hypnose ericksonienne utilise le langage indirect et les métaphores pour communiquer avec l'inconscient. Aujourd'hui, nous apprenons les scripts d'auto-hypnose ericksonienne spécifiques au sommeil.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "box",
    ambientSound: "forest",
    eveningRoutine: "1. Installez-vous confortablement et fixez un point devant vous\n2. Utilisez le script d'induction : 'Vous pouvez remarquer comment vos yeux deviennent lourds...'\n3. Approfondissez avec la métaphore de l'escalier (10 marches vers la relaxation)\n4. Utilisez la suggestion post-hypnotique : 'Chaque soir, quand vous posez la tête sur l'oreiller...'\n5. Méditez avec la méditation du voyage nocturne\n6. Pratiquez la respiration carrée × 6 cycles",
    sleepTip: "L'hypnose ericksonienne utilise des suggestions indirectes ('Vous pourriez remarquer...', 'Il est possible que...') qui contournent la résistance consciente. Une méta-analyse de 2018 montre que l'hypnose améliore le sommeil profond de 80% chez les bons sujets hypnotiques. Même les sujets moins hypnotisables bénéficient de la relaxation profonde induite par le processus.",
    journalPrompt: "Avez-vous réussi à entrer dans un état hypnotique ? Sur une échelle de 0 à 10, à quel niveau de profondeur estimez-vous être allé ? Quelles suggestions ont semblé les plus efficaces ? Comment vous êtes-vous senti au réveil ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 18,
    title: "Jour 18 — Cohérence cardiaque avancée",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La cohérence cardiaque avancée va au-delà de la simple respiration rythmique. Aujourd'hui, nous intégrons la visualisation cardiaque et la pratique HeartMath pour une régulation émotionnelle profonde.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Pratiquez la cohérence cardiaque de base : 5 min (5s inspir / 5s expir)\n2. Ajoutez la visualisation : imaginez votre cœur qui rayonne de lumière dorée\n3. Évoquez une émotion positive (gratitude, amour, paix) pendant la respiration\n4. Méditez avec la méditation de la forêt\n5. Pratiquez 10 min de cohérence cardiaque avancée\n6. Endormez-vous en maintenant la sensation de chaleur dans la poitrine",
    sleepTip: "La technique HeartMath (Quick Coherence) combine respiration rythmique + focus cardiaque + émotion positive. Cette triade active le système nerveux parasympathique, réduit le cortisol de 23% et augmente le DHEA (hormone de vitalité) de 100%. Pratiquer 3 fois par jour (matin, après-midi, soir) crée un état de cohérence physiologique durable qui améliore profondément la qualité du sommeil.",
    journalPrompt: "Comment vous sentez-vous après la cohérence cardiaque avancée ? Avez-vous réussi à évoquer une émotion positive pendant la pratique ? Quelle émotion avez-vous choisie ? Comment cela influence-t-il votre état avant de dormir ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 19,
    title: "Jour 19 — Méditation des 4 éléments",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "La méditation des 4 éléments (terre, eau, feu, air) est une pratique ancestrale qui ancre le corps et calme l'esprit. Aujourd'hui, nous l'adaptons spécifiquement pour l'endormissement.",
    meditationSlug: "pleine-lune",
    breathingExercise: "4-7-8",
    ambientSound: "rain",
    eveningRoutine: "1. Terre : sentez le poids de votre corps sur le matelas, la solidité sous vous\n2. Eau : imaginez une rivière calme qui emporte vos pensées\n3. Feu : visualisez une flamme douce qui réchauffe votre cœur\n4. Air : observez chaque respiration comme une vague qui entre et sort\n5. Méditez avec la méditation de la pleine lune\n6. Pratiquez 5 cycles de 4-7-8 en vous concentrant sur l'élément air",
    sleepTip: "La méditation des 4 éléments active différentes zones cérébrales : la terre stimule l'insula (conscience corporelle), l'eau active le cortex préfrontal (régulation émotionnelle), le feu engage l'amygdale (émotions positives), l'air renforce le cortex cingulaire antérieur (pleine conscience). Cette activation multimodale crée un état de conscience équilibré propice à l'endormissement.",
    journalPrompt: "Quel élément vous a le plus touché ce soir ? Lequel a été le plus difficile à visualiser ? Comment cette méditation a-t-elle influencé votre état mental ? Avez-vous remarqué des sensations physiques particulières ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 20,
    title: "Jour 20 — Pratique du non-faire (Wu Wei)",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "Le Wu Wei taoïste — l'art du non-faire — est peut-être la clé ultime du sommeil. Aujourd'hui, nous apprenons à ne pas essayer de dormir, mais à simplement être, et à laisser le sommeil venir naturellement.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "forest",
    eveningRoutine: "1. Ce soir, ne faites rien pour essayer de dormir\n2. Allongez-vous et observez simplement ce qui se passe\n3. Abandonnez tout effort, toute technique, toute attente\n4. Méditez avec la méditation de gratitude\n5. Pratiquez 5 min de cohérence cardiaque\n6. Laissez le sommeil venir à vous, sans le chercher",
    sleepTip: "Le paradoxe du sommeil : plus vous essayez de dormir, moins vous y arrivez. Le Wu Wei appliqué au sommeil consiste à créer les conditions favorables (rituel du soir, environnement optimal) puis à lâcher prise totalement. C'est l'abandon de l'effort qui permet au sommeil de venir. Comme on ne peut pas forcer une fleur à s'ouvrir, on ne peut pas forcer le sommeil — on peut seulement créer les conditions de son épanouissement.",
    journalPrompt: "Comment vous êtes-vous senti en abandonnant tout effort ce soir ? Était-ce difficile ? Qu'avez-vous observé ? Avez-vous réussi à lâcher prise ? Comment cela a-t-il influencé votre endormissement ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 21,
    title: "Jour 21 — Bilan semaine 3 et intégration",
    theme: "Semaine 3 : Pratiques contemplatives avancées",
    description: "Trois semaines de pratique intensive ! Aujourd'hui, nous intégrons les pratiques contemplatives dans votre programme personnalisé et préparons la semaine 4 de maîtrise et d'autonomie.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Relisez vos notes des 7 derniers jours\n2. Identifiez les 3 pratiques contemplatives les plus transformatrices pour vous\n3. Intégrez-les dans votre programme personnalisé\n4. Méditez avec la méditation du voyage nocturne\n5. Pratiquez la respiration carrée × 8 cycles\n6. Écrivez votre bilan de la semaine 3 et vos intentions pour la semaine 4",
    sleepTip: "Les pratiques contemplatives agissent sur un niveau plus profond que les techniques comportementales : elles transforment votre relation au sommeil et à la conscience. Là où la TCC-I change les comportements, la méditation change la perception. Les deux approches sont complémentaires et synergiques — ensemble, elles produisent des résultats durables que ni l'une ni l'autre ne peut atteindre seule.",
    journalPrompt: "Quelles pratiques contemplatives ont le plus transformé votre rapport au sommeil ? Comment votre relation à l'insomnie a-t-elle évolué ? Qu'est-ce que vous avez découvert sur vous-même au cours de ces 21 jours ?",
    estimatedMinutes: 40,
  },

  // ═══════════════════════════════════════════════════════
  // SEMAINE 4 : INTÉGRATION ET MAÎTRISE
  // ═══════════════════════════════════════════════════════
  {
    dayNumber: 22,
    title: "Jour 22 — Construire votre programme maître",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Vous avez exploré plus de 20 techniques différentes. Aujourd'hui, vous construisez votre programme maître personnalisé — une synthèse unique et optimisée de toutes vos meilleures pratiques.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Listez toutes les techniques essayées et notez-les sur 10\n2. Sélectionnez vos 7-10 meilleures pratiques\n3. Organisez-les en un rituel du soir de 30-45 min\n4. Méditez avec la relaxation profonde\n5. Pratiquez 5 min de cohérence cardiaque\n6. Testez votre programme maître ce soir pour la première fois",
    sleepTip: "Un programme de sommeil optimal comprend : une phase de décompression (2h avant), un rituel du soir (30-45 min) et une phase d'endormissement (10-20 min). La phase de décompression est souvent négligée mais cruciale : elle permet au système nerveux de passer progressivement du mode sympathique (action) au mode parasympathique (repos). Sans elle, même le meilleur rituel du soir sera moins efficace.",
    journalPrompt: "Décrivez votre programme maître personnalisé, étape par étape. Pourquoi avez-vous choisi ces pratiques spécifiques ? Comment vous sentez-vous après avoir testé votre programme ce soir ?",
    estimatedMinutes: 40,
  },
  {
    dayNumber: 23,
    title: "Jour 23 — Gestion des voyages et décalages horaires",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Les voyages et décalages horaires peuvent perturber des semaines de progrès. Aujourd'hui, nous développons votre protocole de voyage pour maintenir la qualité de votre sommeil partout dans le monde.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Créez votre 'kit de voyage sommeil' : masque, bouchons, tisane, huile essentielle\n2. Apprenez le protocole de récupération jet lag (lumière, mélatonine, timing)\n3. Méditez avec la méditation de la forêt\n4. Pratiquez 5 cycles de 4-7-8\n5. Pratiquez votre rituel du soir même en déplacement (version courte 15 min)\n6. Notez votre protocole de voyage dans le journal",
    sleepTip: "Pour les vols vers l'est (plus difficiles) : adoptez l'heure de destination dès l'embarquement, exposez-vous à la lumière vive à l'heure du matin local, prenez 0,5mg de mélatonine à l'heure du coucher local pendant 3-5 jours. Pour les vols vers l'ouest : restez éveillé jusqu'à l'heure normale du coucher local, évitez les siestes longues. La mélatonine à faible dose (0,5mg) est plus efficace que les doses élevées (3-5mg).",
    journalPrompt: "Comment gérez-vous habituellement les voyages et décalages horaires ? Quel impact ont-ils sur votre sommeil ? Quel protocole allez-vous adopter pour votre prochain voyage ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 24,
    title: "Jour 24 — Sommeil et performance cognitive",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Le sommeil est le supercarburant de la performance cognitive. Aujourd'hui, nous explorons comment optimiser votre sommeil pour maximiser créativité, mémoire, prise de décision et intelligence émotionnelle.",
    meditationSlug: "pleine-lune",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Avant de dormir, révisez mentalement les apprentissages importants de la journée\n2. Posez une question à votre inconscient : 'Quelle est la solution à [problème] ?'\n3. Méditez avec la méditation de la pleine lune\n4. Pratiquez la respiration carrée × 8 cycles\n5. Notez vos insights du matin immédiatement au réveil\n6. Planifiez vos tâches cognitives importantes pour le matin (pic de performance)",
    sleepTip: "Le sommeil paradoxal (REM) est le moteur de la créativité et de la résolution de problèmes. Les scientifiques appellent cela 'sleep to solve' : votre cerveau continue de traiter les problèmes pendant le sommeil, créant des connexions inattendues. Thomas Edison, Salvador Dalí et Paul McCartney ont tous rapporté avoir trouvé leurs meilleures idées au réveil. Notez vos rêves et insights matinaux.",
    journalPrompt: "Avez-vous déjà trouvé une solution à un problème après une nuit de sommeil ? Comment votre sommeil influence-t-il votre performance cognitive quotidienne ? Quelle question allez-vous poser à votre inconscient ce soir ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 25,
    title: "Jour 25 — Sommeil et régulation émotionnelle",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Le manque de sommeil amplifie les émotions négatives de 60% et réduit la résilience émotionnelle. Aujourd'hui, nous explorons le lien profond entre sommeil et santé émotionnelle.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Pratiquez l'EMDR léger : tapotements bilatéraux sur les genoux pendant 5 min\n2. Identifiez et nommez vos émotions du jour (technique de labeling)\n3. Méditez avec la méditation de gratitude\n4. Pratiquez 5 min de cohérence cardiaque\n5. Pratiquez la technique de la 'douche émotionnelle' : imaginez vos émotions se dissoudre sous une pluie dorée\n6. Endormez-vous dans un état de légèreté émotionnelle",
    sleepTip: "Le sommeil paradoxal joue un rôle crucial dans le traitement émotionnel : il 'recalibrate' l'amygdale (centre des émotions) et réduit la charge émotionnelle des souvenirs difficiles. C'est pourquoi 'la nuit porte conseil' : les problèmes émotionnels semblent moins lourds après une bonne nuit. Inversement, l'insomnie chronique augmente le risque de dépression de 400% et d'anxiété de 300%.",
    journalPrompt: "Comment votre sommeil influence-t-il vos émotions ? Les jours où vous dormez bien, comment vous sentez-vous émotionnellement ? Et les jours où vous dormez mal ? Quelles émotions non traitées pourraient perturber votre sommeil ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 26,
    title: "Jour 26 — Sommeil et relations",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Le sommeil influence profondément nos relations : empathie, communication, patience, désir. Aujourd'hui, nous explorons comment optimiser votre sommeil pour améliorer la qualité de vos relations.",
    meditationSlug: "voyage-nocturne",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Si vous dormez avec un partenaire, discutez de vos besoins de sommeil respectifs\n2. Créez des rituels de sommeil compatibles avec votre vie de couple\n3. Méditez avec la méditation du voyage nocturne\n4. Pratiquez 5 cycles de 4-7-8\n5. Pratiquez la méditation de la bienveillance (metta) : envoyez de l'amour à vous-même et aux autres\n6. Endormez-vous dans un sentiment de connexion et d'amour",
    sleepTip: "Une étude de l'Université de Berkeley montre que le manque de sommeil réduit l'empathie de 40% et augmente les conflits relationnels. Les couples qui dorment bien ensemble rapportent 10% de satisfaction relationnelle en plus. Si vous avez des rythmes différents, négociez : heure de coucher flexible, lumière de lecture, bruit blanc. La qualité du sommeil est un investissement dans la qualité de vos relations.",
    journalPrompt: "Comment votre sommeil influence-t-il vos relations ? Êtes-vous plus patient, empathique et présent quand vous dormez bien ? Comment pouvez-vous créer des conditions de sommeil qui respectent les besoins de tous ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 27,
    title: "Jour 27 — Sommeil et longévité",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Le sommeil est le pilier le plus important de la longévité en bonne santé. Aujourd'hui, nous explorons les liens entre sommeil, vieillissement et prévention des maladies chroniques.",
    meditationSlug: "relaxation-profonde",
    breathingExercise: "box",
    ambientSound: "ocean",
    eveningRoutine: "1. Pratiquez la méditation de la gratitude pour votre corps et sa santé\n2. Visualisez votre corps se régénérer et se réparer pendant le sommeil\n3. Méditez avec la relaxation profonde\n4. Pratiquez la respiration carrée × 8 cycles\n5. Prenez vos compléments de longévité si applicable (NMN, resvératrol, etc.)\n6. Endormez-vous avec l'intention de permettre à votre corps de se régénérer pleinement",
    sleepTip: "Dormir moins de 6h par nuit augmente le risque de maladies cardiovasculaires de 200%, de diabète de type 2 de 50%, d'obésité de 55% et de cancer de 40%. À l'inverse, 7-9h de sommeil de qualité activent les gènes de réparation cellulaire, allongent les télomères (marqueurs de longévité) et réduisent l'inflammation chronique. Le sommeil est votre meilleur médicament anti-âge.",
    journalPrompt: "Comment votre sommeil influence-t-il votre santé à long terme ? Quelles maladies ou conditions de santé voulez-vous prévenir ? Comment cela renforce-t-il votre motivation à bien dormir ?",
    estimatedMinutes: 35,
  },
  {
    dayNumber: 28,
    title: "Jour 28 — Transmission et enseignement",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "La meilleure façon de consolider un apprentissage est de l'enseigner. Aujourd'hui, vous devenez un ambassadeur du sommeil — vous partagez vos connaissances et aidez ceux qui vous entourent.",
    meditationSlug: "foret-apaisante",
    breathingExercise: "coherence",
    ambientSound: "rain",
    eveningRoutine: "1. Partagez une technique de sommeil avec un proche (famille, ami, collègue)\n2. Expliquez l'importance du sommeil en 3 minutes\n3. Méditez avec la méditation de la forêt\n4. Pratiquez 5 min de cohérence cardiaque\n5. Réfléchissez à comment vous pouvez continuer à apprendre sur le sommeil\n6. Notez les ressources (livres, podcasts, études) que vous voulez explorer",
    sleepTip: "Enseigner consolide l'apprentissage de 90% selon la pyramide d'apprentissage d'Edgar Dale. En expliquant les techniques de sommeil à d'autres, vous ancrez vos propres connaissances et créez un cercle vertueux. De plus, aider les autres active le système de récompense dopaminergique, renforçant votre propre motivation à maintenir vos habitudes.",
    journalPrompt: "À qui avez-vous parlé du sommeil aujourd'hui ? Comment ont-ils réagi ? Qu'avez-vous appris en essayant d'expliquer ce que vous savez ? Quelles ressources voulez-vous explorer pour approfondir votre maîtrise ?",
    estimatedMinutes: 30,
  },
  {
    dayNumber: 29,
    title: "Jour 29 — Évaluation finale et mesure des progrès",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Avant-dernière étape ! Aujourd'hui, nous réalisons une évaluation complète de vos progrès sur 29 jours, mesurons tous les indicateurs et préparons votre plan de maintenance à long terme.",
    meditationSlug: "pleine-lune",
    breathingExercise: "4-7-8",
    ambientSound: "forest",
    eveningRoutine: "1. Complétez à nouveau le questionnaire PSQI et comparez avec le jour 1\n2. Calculez votre efficacité de sommeil moyenne sur les 4 semaines\n3. Mesurez tous vos indicateurs : latence, durée, réveils, qualité subjective\n4. Méditez avec la méditation de la pleine lune\n5. Pratiquez 5 cycles de 4-7-8\n6. Écrivez votre plan de maintenance pour les 6 prochains mois",
    sleepTip: "Les indicateurs clés à mesurer : efficacité de sommeil (objectif > 85%), latence d'endormissement (objectif < 20 min), nombre de réveils (objectif < 2), durée totale (objectif 7-9h), qualité subjective (objectif > 7/10), fonctionnement diurne (énergie, concentration, humeur). Si vous avez atteint 3 de ces 6 objectifs, vous avez fait des progrès significatifs. Si vous en avez atteint 5 ou 6, vous êtes un maître du sommeil.",
    journalPrompt: "Comparez vos scores du jour 1 et du jour 29. Quels indicateurs se sont le plus améliorés ? Lesquels nécessitent encore du travail ? De quoi êtes-vous le plus fier ? Quel est votre plan pour les 6 prochains mois ?",
    estimatedMinutes: 45,
  },
  {
    dayNumber: 30,
    title: "Jour 30 — Maître du sommeil : célébration et engagement",
    theme: "Semaine 4 : Intégration et maîtrise",
    description: "Vous avez terminé le programme ultime de 30 jours. Vous êtes maintenant un Maître du Sommeil — vous possédez les connaissances, les outils et l'expérience pour transformer votre sommeil et celui des autres. Célébrez cette victoire extraordinaire.",
    meditationSlug: "gratitude-nocturne",
    breathingExercise: "coherence",
    ambientSound: "ocean",
    eveningRoutine: "1. Relisez l'intégralité de votre journal de 30 jours\n2. Comparez votre sommeil du jour 1 et du jour 30 — mesurez votre transformation\n3. Célébrez : offrez-vous quelque chose de symbolique et significatif\n4. Méditez avec la méditation de gratitude — la plus longue et la plus profonde de votre programme\n5. Pratiquez 10 min de cohérence cardiaque\n6. Écrivez une lettre à votre futur vous dans 1 an sur votre sommeil et votre vie",
    sleepTip: "Vous avez accompli quelque chose que moins de 1% des gens font : vous avez consacré 30 jours à transformer fondamentalement votre sommeil. Votre cerveau a créé de nouvelles connexions neuronales, votre système nerveux s'est rééquilibré, vos habitudes se sont ancrées. Maintenant, votre mission est de maintenir et d'approfondir. Le sommeil est un voyage, pas une destination. Continuez à apprendre, à pratiquer, à vous améliorer.",
    journalPrompt: "Quelle est la plus grande transformation que vous avez vécue au cours de ces 30 jours ? Comment votre vie a-t-elle changé grâce à un meilleur sommeil ? Quel est votre message pour quelqu'un qui commence ce programme ? Écrivez une lettre à votre futur vous dans 1 an.",
    estimatedMinutes: 50,
  },
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  console.log("🌙 Enrichissement des programmes 21j et 30j...\n");

  const allDays = [
    ...TRANSFORMATION_DAYS.map(d => ({ ...d, programSlug: "transformation-sommeil" })),
    ...MAITRE_DAYS.map(d => ({ ...d, programSlug: "maitre-sommeil" })),
  ];

  console.log(`📅 Mise à jour de ${allDays.length} jours (21 + 30)...`);

  let success = 0;
  let errors = 0;

  for (const day of allDays) {
    try {
      await db.insert(programDays).values(day).onDuplicateKeyUpdate({
        set: {
          title: day.title,
          theme: day.theme,
          description: day.description,
          meditationSlug: day.meditationSlug,
          breathingExercise: day.breathingExercise,
          ambientSound: day.ambientSound,
          eveningRoutine: day.eveningRoutine,
          sleepTip: day.sleepTip,
          journalPrompt: day.journalPrompt,
          estimatedMinutes: day.estimatedMinutes,
        },
      });
      success++;
      if (day.dayNumber === 1 || day.dayNumber % 7 === 0 || day.dayNumber === TRANSFORMATION_DAYS.length || day.dayNumber === MAITRE_DAYS.length) {
        console.log(`  ✅ [${day.programSlug}] Jour ${day.dayNumber} — ${day.title}`);
      }
    } catch (e) {
      errors++;
      console.error(`  ❌ Erreur [${day.programSlug}] Jour ${day.dayNumber}:`, e);
    }
  }

  console.log(`\n✅ ${success} jours mis à jour avec succès !`);
  if (errors > 0) console.log(`⚠️  ${errors} erreurs`);
  console.log("\n🎉 Enrichissement terminé !");
  process.exit(0);
}

seed().catch(console.error);
